// Copyright (C) 2026 Intel Corporation
// SPDX-FileCopyrightText: 2025 Canonical Ltd
// SPDX-License-Identifier: Apache-2.0

/*
WebConsole NFConfig API

API for managing access, mobility, policy, session and PLMN information.
API version: 1.0.0

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package nfConfigApi

import (
	"encoding/json"
	"maps"

	"github.com/omec-project/openapi/v2"
)

// checks if the PlmnId type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &PlmnId{}

// PlmnId struct for PlmnId
type PlmnId struct {
	Mcc                  string `json:"mcc" yaml:"mcc"`
	Mnc                  string `json:"mnc" yaml:"mnc"`
	AdditionalProperties map[string]any
}

type _PlmnId PlmnId

// NewPlmnId instantiates a new PlmnId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlmnId(mcc string, mnc string) *PlmnId {
	this := PlmnId{}
	this.Mcc = mcc
	this.Mnc = mnc
	return &this
}

// NewPlmnIdWithDefaults instantiates a new PlmnId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlmnIdWithDefaults() *PlmnId {
	this := PlmnId{}
	return &this
}

// GetMcc returns the Mcc field value
func (o *PlmnId) GetMcc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mcc
}

// GetMccOk returns a tuple with the Mcc field value
// and a boolean to check if the value has been set.
func (o *PlmnId) GetMccOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mcc, true
}

// SetMcc sets field value
func (o *PlmnId) SetMcc(v string) {
	o.Mcc = v
}

// GetMnc returns the Mnc field value
func (o *PlmnId) GetMnc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mnc
}

// GetMncOk returns a tuple with the Mnc field value
// and a boolean to check if the value has been set.
func (o *PlmnId) GetMncOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mnc, true
}

// SetMnc sets field value
func (o *PlmnId) SetMnc(v string) {
	o.Mnc = v
}

func (o PlmnId) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlmnId) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	toSerialize["mcc"] = o.Mcc
	toSerialize["mnc"] = o.Mnc

	maps.Copy(toSerialize, o.AdditionalProperties)

	return toSerialize, nil
}

func (o *PlmnId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mcc",
		"mnc",
	}

	allProperties := make(map[string]any)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return openapi.ReportError("no value given for required property %v", requiredProperty)
		}
	}

	varPlmnId := _PlmnId{}

	err = json.Unmarshal(data, &varPlmnId)

	if err != nil {
		return err
	}

	*o = PlmnId(varPlmnId)

	additionalProperties := make(map[string]any)

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mcc")
		delete(additionalProperties, "mnc")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlmnId struct {
	value *PlmnId
	isSet bool
}

func (v NullablePlmnId) Get() *PlmnId {
	return v.value
}

func (v *NullablePlmnId) Set(val *PlmnId) {
	v.value = val
	v.isSet = true
}

func (v NullablePlmnId) IsSet() bool {
	return v.isSet
}

func (v *NullablePlmnId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlmnId(val *PlmnId) *NullablePlmnId {
	return &NullablePlmnId{value: val, isSet: true}
}

func (v NullablePlmnId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlmnId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
