// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Testing SubscriptionDeletionAPIService

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
)

func Test_Nudm_SDM_SubscriptionDeletionAPIService(t *testing.T) {
	t.Run("Test SubscriptionDeletionAPIService Unsubscribe", func(t *testing.T) {
		var ueId string
		var subscriptionId string

		mockServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != http.MethodDelete {
				t.Errorf("Expected HTTP method %s, but got: %s", http.MethodDelete, r.Method)
			}
			w.WriteHeader(http.StatusNoContent)
		}))
		defer mockServer.Close()

		configuration := NewConfiguration()
		configuration.Servers = ServerConfigurations{
			{
				URL: mockServer.URL,
			},
		}
		apiClient := NewAPIClient(configuration)

		httpRes, err := apiClient.SubscriptionDeletionAPI.Unsubscribe(context.Background(), ueId, subscriptionId).Execute()

		if err != nil {
			t.Fatalf("Expected no error, but got: %v", err)
		}
		if httpRes.StatusCode < 200 || httpRes.StatusCode >= 300 {
			t.Errorf("Expected 2xx status code, but got: %d", httpRes.StatusCode)
		}
	})

}
