// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
)

type RetrievalOfSharedDataAPI interface {

	/*
		GetSharedData retrieve shared data

			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@return ApiGetSharedDataRequest
	*/
	GetSharedData(ctx context.Context) ApiGetSharedDataRequest

	// GetSharedDataExecute executes the request
	//   @return []SharedDataUdm
	GetSharedDataExecute(r ApiGetSharedDataRequest) ([]models.SharedDataUdm, *http.Response, error)
}

// RetrievalOfSharedDataAPIService RetrievalOfSharedDataAPI service
type RetrievalOfSharedDataAPIService service

type ApiGetSharedDataRequest struct {
	ctx                context.Context
	ApiService         RetrievalOfSharedDataAPI
	sharedDataIds      *[]string
	supportedFeatures  *string
	supportedFeatures2 *string
	ifNoneMatch        *string
	ifModifiedSince    *string
}

// List of shared data ids
func (r ApiGetSharedDataRequest) SharedDataIds(sharedDataIds []string) ApiGetSharedDataRequest {
	r.sharedDataIds = &sharedDataIds
	return r
}

// Supported Features; this query parameter should not be used
// Deprecated
func (r ApiGetSharedDataRequest) SupportedFeatures(supportedFeatures string) ApiGetSharedDataRequest {
	r.supportedFeatures = &supportedFeatures
	return r
}

// Supported Features
func (r ApiGetSharedDataRequest) SupportedFeatures2(supportedFeatures2 string) ApiGetSharedDataRequest {
	r.supportedFeatures2 = &supportedFeatures2
	return r
}

// Validator for conditional requests, as described in RFC 9110, 3.2
func (r ApiGetSharedDataRequest) IfNoneMatch(ifNoneMatch string) ApiGetSharedDataRequest {
	r.ifNoneMatch = &ifNoneMatch
	return r
}

// Validator for conditional requests, as described in RFC 9110, 3.3
func (r ApiGetSharedDataRequest) IfModifiedSince(ifModifiedSince string) ApiGetSharedDataRequest {
	r.ifModifiedSince = &ifModifiedSince
	return r
}

func (r ApiGetSharedDataRequest) Execute() ([]models.SharedDataUdm, *http.Response, error) {
	return r.ApiService.GetSharedDataExecute(r)
}

/*
GetSharedData retrieve shared data

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetSharedDataRequest
*/
func (a *RetrievalOfSharedDataAPIService) GetSharedData(ctx context.Context) ApiGetSharedDataRequest {
	return ApiGetSharedDataRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []SharedDataUdm
func (a *RetrievalOfSharedDataAPIService) GetSharedDataExecute(r ApiGetSharedDataRequest) ([]models.SharedDataUdm, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    any
		formFiles           []formFile
		localVarReturnValue []models.SharedDataUdm
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetrievalOfSharedDataAPIService.GetSharedData")
	if err != nil {
		return localVarReturnValue, nil, &openapi.GenericOpenAPIError{RawError: err.Error()}
	}

	localVarPath := localBasePath + "/shared-data"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.sharedDataIds == nil {
		return localVarReturnValue, nil, openapi.ReportError("sharedDataIds is required and must be specified")
	}
	if len(*r.sharedDataIds) < 1 {
		return localVarReturnValue, nil, openapi.ReportError("sharedDataIds must have at least 1 elements")
	}

	openapi.ParameterAddToHeaderOrQuery(localVarQueryParams, "shared-data-ids", r.sharedDataIds, "form", "csv")
	if r.supportedFeatures != nil {
		openapi.ParameterAddToHeaderOrQuery(localVarQueryParams, "supportedFeatures", r.supportedFeatures, "form", "")
	}
	if r.supportedFeatures2 != nil {
		openapi.ParameterAddToHeaderOrQuery(localVarQueryParams, "supported-features", r.supportedFeatures2, "form", "")
	}
	// set Content-Type header
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := openapi.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := openapi.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ifNoneMatch != nil {
		openapi.ParameterAddToHeaderOrQuery(localVarHeaderParams, "If-None-Match", r.ifNoneMatch, "simple", "")
	}
	if r.ifModifiedSince != nil {
		openapi.ParameterAddToHeaderOrQuery(localVarHeaderParams, "If-Modified-Since", r.ifModifiedSince, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
