// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_SDM

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"strings"

	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
)

type ProvidingAcknowledgementOfSteeringOfRoamingAPI interface {

	/*
		SorAckInfo Nudm_Sdm Info service operation

			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param supi Identifier of the UE
			@return ApiSorAckInfoRequest
	*/
	SorAckInfo(ctx context.Context, supi string) ApiSorAckInfoRequest

	// SorAckInfoExecute executes the request
	SorAckInfoExecute(r ApiSorAckInfoRequest) (*http.Response, error)
}

// ProvidingAcknowledgementOfSteeringOfRoamingAPIService ProvidingAcknowledgementOfSteeringOfRoamingAPI service
type ProvidingAcknowledgementOfSteeringOfRoamingAPIService service

type ApiSorAckInfoRequest struct {
	ctx             context.Context
	ApiService      ProvidingAcknowledgementOfSteeringOfRoamingAPI
	supi            string
	acknowledgeInfo *models.AcknowledgeInfo
}

func (r ApiSorAckInfoRequest) AcknowledgeInfo(acknowledgeInfo models.AcknowledgeInfo) ApiSorAckInfoRequest {
	r.acknowledgeInfo = &acknowledgeInfo
	return r
}

func (r ApiSorAckInfoRequest) Execute() (*http.Response, error) {
	return r.ApiService.SorAckInfoExecute(r)
}

/*
SorAckInfo Nudm_Sdm Info service operation

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param supi Identifier of the UE
	@return ApiSorAckInfoRequest
*/
func (a *ProvidingAcknowledgementOfSteeringOfRoamingAPIService) SorAckInfo(ctx context.Context, supi string) ApiSorAckInfoRequest {
	return ApiSorAckInfoRequest{
		ApiService: a,
		ctx:        ctx,
		supi:       supi,
	}
}

// Execute executes the request
func (a *ProvidingAcknowledgementOfSteeringOfRoamingAPIService) SorAckInfoExecute(r ApiSorAckInfoRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPut
		localVarPostBody   any
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProvidingAcknowledgementOfSteeringOfRoamingAPIService.SorAckInfo")
	if err != nil {
		return nil, &openapi.GenericOpenAPIError{RawError: err.Error()}
	}

	localVarPath := localBasePath + "/{supi}/am-data/sor-ack"
	localVarPath = strings.ReplaceAll(localVarPath, "{"+"supi"+"}", url.PathEscape(openapi.ParameterValueToString(r.supi, "supi")))

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// set Content-Type header
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}
	localVarHTTPContentType := openapi.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := openapi.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.acknowledgeInfo
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 411 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 413 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
