// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Testing AuthenticationUPUDocumentAPIService

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudr_DR

import (
	"context"
	"net/http"
	"net/http/httptest"
	"testing"
)

func Test_Nudr_DR_AuthenticationUPUDocumentAPIService(t *testing.T) {
	t.Run("Test AuthenticationUPUDocumentAPIService CreateAuthenticationUPU", func(t *testing.T) {
		t.Skip("skip autogenerated mock test for operations with required non-path parameter upuDataUdr")
		var ueId string

		mockServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != http.MethodPut {
				t.Errorf("Expected HTTP method %s, but got: %s", http.MethodPut, r.Method)
			}
			w.WriteHeader(http.StatusNoContent)
		}))
		defer mockServer.Close()

		configuration := NewConfiguration()
		configuration.Servers = ServerConfigurations{
			{
				URL: mockServer.URL,
			},
		}
		apiClient := NewAPIClient(configuration)

		httpRes, err := apiClient.AuthenticationUPUDocumentAPI.CreateAuthenticationUPU(context.Background(), ueId).Execute()

		if err != nil {
			t.Fatalf("Expected no error, but got: %v", err)
		}
		if httpRes.StatusCode < 200 || httpRes.StatusCode >= 300 {
			t.Errorf("Expected 2xx status code, but got: %d", httpRes.StatusCode)
		}
	})

	t.Run("Test AuthenticationUPUDocumentAPIService QueryAuthUPU", func(t *testing.T) {
		t.Skip("skip autogenerated mock test for operations with response bodies")
		var ueId string

		mockServer := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != http.MethodGet {
				t.Errorf("Expected HTTP method %s, but got: %s", http.MethodGet, r.Method)
			}
			w.WriteHeader(http.StatusNoContent)
		}))
		defer mockServer.Close()

		configuration := NewConfiguration()
		configuration.Servers = ServerConfigurations{
			{
				URL: mockServer.URL,
			},
		}
		apiClient := NewAPIClient(configuration)

		resp, httpRes, err := apiClient.AuthenticationUPUDocumentAPI.QueryAuthUPU(context.Background(), ueId).Execute()

		if err != nil {
			t.Fatalf("Expected no error, but got: %v", err)
		}
		if resp == nil {
			t.Fatal("Expected response to be non-nil")
		}
		if httpRes.StatusCode < 200 || httpRes.StatusCode >= 300 {
			t.Errorf("Expected 2xx status code, but got: %d", httpRes.StatusCode)
		}
	})

}
