// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudr_DR

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"strings"

	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
)

type ProSeServiceSubscriptionDataAPI interface {

	/*
		QueryPorseData Retrieves the subscribed ProSe service Data of a UE

			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param ueId UE id
			@return ApiQueryPorseDataRequest
	*/
	QueryPorseData(ctx context.Context, ueId string) ApiQueryPorseDataRequest

	// QueryPorseDataExecute executes the request
	//   @return ProseSubscriptionData
	QueryPorseDataExecute(r ApiQueryPorseDataRequest) (*models.ProseSubscriptionData, *http.Response, error)
}

// ProSeServiceSubscriptionDataAPIService ProSeServiceSubscriptionDataAPI service
type ProSeServiceSubscriptionDataAPIService service

type ApiQueryPorseDataRequest struct {
	ctx               context.Context
	ApiService        ProSeServiceSubscriptionDataAPI
	ueId              string
	supportedFeatures *string
	ifNoneMatch       *string
	ifModifiedSince   *string
}

// Supported Features
func (r ApiQueryPorseDataRequest) SupportedFeatures(supportedFeatures string) ApiQueryPorseDataRequest {
	r.supportedFeatures = &supportedFeatures
	return r
}

// Validator for conditional requests, as described in RFC 9110, 13.1.2
func (r ApiQueryPorseDataRequest) IfNoneMatch(ifNoneMatch string) ApiQueryPorseDataRequest {
	r.ifNoneMatch = &ifNoneMatch
	return r
}

// Validator for conditional requests, as described in RFC 9110, 13.1.3
func (r ApiQueryPorseDataRequest) IfModifiedSince(ifModifiedSince string) ApiQueryPorseDataRequest {
	r.ifModifiedSince = &ifModifiedSince
	return r
}

func (r ApiQueryPorseDataRequest) Execute() (*models.ProseSubscriptionData, *http.Response, error) {
	return r.ApiService.QueryPorseDataExecute(r)
}

/*
QueryPorseData Retrieves the subscribed ProSe service Data of a UE

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param ueId UE id
	@return ApiQueryPorseDataRequest
*/
func (a *ProSeServiceSubscriptionDataAPIService) QueryPorseData(ctx context.Context, ueId string) ApiQueryPorseDataRequest {
	return ApiQueryPorseDataRequest{
		ApiService: a,
		ctx:        ctx,
		ueId:       ueId,
	}
}

// Execute executes the request
//
//	@return ProseSubscriptionData
func (a *ProSeServiceSubscriptionDataAPIService) QueryPorseDataExecute(r ApiQueryPorseDataRequest) (*models.ProseSubscriptionData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    any
		formFiles           []formFile
		localVarReturnValue *models.ProseSubscriptionData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ProSeServiceSubscriptionDataAPIService.QueryPorseData")
	if err != nil {
		return localVarReturnValue, nil, &openapi.GenericOpenAPIError{RawError: err.Error()}
	}

	localVarPath := localBasePath + "/subscription-data/{ueId}/prose-data"
	localVarPath = strings.ReplaceAll(localVarPath, "{"+"ueId"+"}", url.PathEscape(openapi.ParameterValueToString(r.ueId, "ueId")))

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.supportedFeatures != nil {
		openapi.ParameterAddToHeaderOrQuery(localVarQueryParams, "supported-features", r.supportedFeatures, "", "")
	}
	// set Content-Type header
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := openapi.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := openapi.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ifNoneMatch != nil {
		openapi.ParameterAddToHeaderOrQuery(localVarHeaderParams, "If-None-Match", r.ifNoneMatch, "", "")
	}
	if r.ifModifiedSince != nil {
		openapi.ParameterAddToHeaderOrQuery(localVarHeaderParams, "If-Modified-Since", r.ifModifiedSince, "", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
