// SPDX-FileCopyrightText: 2025 Canonical Ltd
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package webconsole

type Arp struct {
	PriorityLevel int32 `json:"priorityLevel,omitempty"`

	Pc string `json:"pc,omitempty"`

	Pv string `json:"pv,omitempty"`
}
