// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nsmf_PDUSession

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"os"

	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
)

type PDUSessionsCollectionAPI interface {

	/*
		PostPduSessions Create

			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@return ApiPostPduSessionsRequest
	*/
	PostPduSessions(ctx context.Context) ApiPostPduSessionsRequest

	// PostPduSessionsExecute executes the request
	//   @return PduSessionCreatedData
	PostPduSessionsExecute(r ApiPostPduSessionsRequest) (*models.PduSessionCreatedData, *http.Response, error)
}

// PDUSessionsCollectionAPIService PDUSessionsCollectionAPI service
type PDUSessionsCollectionAPIService service

type ApiPostPduSessionsRequest struct {
	ctx                       context.Context
	ApiService                PDUSessionsCollectionAPI
	pduSessionCreateData      *models.PduSessionCreateData
	binaryDataN1SmInfoFromUe  *os.File
	binaryDataUnknownN1SmInfo *os.File
}

// representation of the PDU session to be created in the H-SMF or SMF
func (r ApiPostPduSessionsRequest) PduSessionCreateData(pduSessionCreateData models.PduSessionCreateData) ApiPostPduSessionsRequest {
	r.pduSessionCreateData = &pduSessionCreateData
	return r
}

func (r ApiPostPduSessionsRequest) BinaryDataN1SmInfoFromUe(binaryDataN1SmInfoFromUe *os.File) ApiPostPduSessionsRequest {
	r.binaryDataN1SmInfoFromUe = binaryDataN1SmInfoFromUe
	return r
}

func (r ApiPostPduSessionsRequest) BinaryDataUnknownN1SmInfo(binaryDataUnknownN1SmInfo *os.File) ApiPostPduSessionsRequest {
	r.binaryDataUnknownN1SmInfo = binaryDataUnknownN1SmInfo
	return r
}

func (r ApiPostPduSessionsRequest) Execute() (*models.PduSessionCreatedData, *http.Response, error) {
	return r.ApiService.PostPduSessionsExecute(r)
}

/*
PostPduSessions Create

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiPostPduSessionsRequest
*/
func (a *PDUSessionsCollectionAPIService) PostPduSessions(ctx context.Context) ApiPostPduSessionsRequest {
	return ApiPostPduSessionsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return PduSessionCreatedData
func (a *PDUSessionsCollectionAPIService) PostPduSessionsExecute(r ApiPostPduSessionsRequest) (*models.PduSessionCreatedData, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    any
		formFiles           []formFile
		localVarReturnValue *models.PduSessionCreatedData
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PDUSessionsCollectionAPIService.PostPduSessions")
	if err != nil {
		return localVarReturnValue, nil, &openapi.GenericOpenAPIError{RawError: err.Error()}
	}

	localVarPath := localBasePath + "/pdu-sessions"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.pduSessionCreateData == nil {
		return localVarReturnValue, nil, openapi.ReportError("pduSessionCreateData is required and must be specified")
	}

	// set Content-Type header
	localVarHTTPContentType := "application/json"
	if r.binaryDataN1SmInfoFromUe != nil || r.binaryDataUnknownN1SmInfo != nil {
		localVarHTTPContentType = "multipart/related"
	}
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "multipart/related", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := openapi.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	var binaryDataN1SmInfoFromUeLocalVarFormFileName string
	var binaryDataN1SmInfoFromUeLocalVarFileName string
	var binaryDataN1SmInfoFromUeLocalVarFileBytes []byte

	binaryDataN1SmInfoFromUeLocalVarFormFileName = "binaryDataN1SmInfoFromUe"
	binaryDataN1SmInfoFromUeLocalVarFile := r.binaryDataN1SmInfoFromUe

	if binaryDataN1SmInfoFromUeLocalVarFile != nil {
		fbs, _ := io.ReadAll(binaryDataN1SmInfoFromUeLocalVarFile)

		binaryDataN1SmInfoFromUeLocalVarFileBytes = fbs
		binaryDataN1SmInfoFromUeLocalVarFileName = binaryDataN1SmInfoFromUeLocalVarFile.Name()
		binaryDataN1SmInfoFromUeLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: binaryDataN1SmInfoFromUeLocalVarFileBytes, fileName: binaryDataN1SmInfoFromUeLocalVarFileName, formFileName: binaryDataN1SmInfoFromUeLocalVarFormFileName, contentType: "application/vnd.3gpp.5gnas"})
	}
	var binaryDataUnknownN1SmInfoLocalVarFormFileName string
	var binaryDataUnknownN1SmInfoLocalVarFileName string
	var binaryDataUnknownN1SmInfoLocalVarFileBytes []byte

	binaryDataUnknownN1SmInfoLocalVarFormFileName = "binaryDataUnknownN1SmInfo"
	binaryDataUnknownN1SmInfoLocalVarFile := r.binaryDataUnknownN1SmInfo

	if binaryDataUnknownN1SmInfoLocalVarFile != nil {
		fbs, _ := io.ReadAll(binaryDataUnknownN1SmInfoLocalVarFile)

		binaryDataUnknownN1SmInfoLocalVarFileBytes = fbs
		binaryDataUnknownN1SmInfoLocalVarFileName = binaryDataUnknownN1SmInfoLocalVarFile.Name()
		binaryDataUnknownN1SmInfoLocalVarFile.Close()
		formFiles = append(formFiles, formFile{fileBytes: binaryDataUnknownN1SmInfoLocalVarFileBytes, fileName: binaryDataUnknownN1SmInfoLocalVarFileName, formFileName: binaryDataUnknownN1SmInfoLocalVarFormFileName, contentType: "application/vnd.3gpp.5gnas"})
	}
	if r.pduSessionCreateData != nil {
		paramJson, err := openapi.ParameterToJson(*r.pduSessionCreateData)
		if err != nil {
			return localVarReturnValue, nil, err
		}
		localVarFormParams.Add("jsonData", paramJson)
	}
	if !(r.binaryDataN1SmInfoFromUe != nil || r.binaryDataUnknownN1SmInfo != nil) {
		// body params
		localVarPostBody = r.pduSessionCreateData
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 307 {
			var v models.RedirectResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 308 {
			var v models.RedirectResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v models.PduSessionCreateError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v models.ExtProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v models.PduSessionCreateError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v models.PduSessionCreateError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 411 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 413 {
			var v models.ExtProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v models.ExtProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v models.ExtProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v models.PduSessionCreateError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v models.ExtProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v models.PduSessionCreateError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 504 {
			var v models.PduSessionCreateError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
