// SPDX-FileCopyrightText: 2025 Canonical Ltd
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * WebConsole NFConfig API
 *
 * API for managing access, mobility, policy, session and PLMN information.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type Status string

const (
	STATUS_ENABLED_UPLINK   Status = "ENABLED-UPLINK"
	STATUS_ENABLED_DOWNLINK Status = "ENABLED-DOWNLINK"
	STATUS_ENABLED          Status = "ENABLED"
	STATUS_DISABLED         Status = "DISABLED"
	STATUS_REMOVED          Status = "REMOVED"
)
