// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_UECM

Nudm Context Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Nudm_UECM

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"strings"

	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
)

type RetrieveSMFRegistrationAPI interface {

	/*
		RetrieveSmfRegistration get an SMF registration

			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param ueId Identifier of the UE
			@param pduSessionId Identifier of the PDU session
			@return ApiRetrieveSmfRegistrationRequest
	*/
	RetrieveSmfRegistration(ctx context.Context, ueId string, pduSessionId int32) ApiRetrieveSmfRegistrationRequest

	// RetrieveSmfRegistrationExecute executes the request
	//   @return SmfRegistration
	RetrieveSmfRegistrationExecute(r ApiRetrieveSmfRegistrationRequest) (*models.SmfRegistration, *http.Response, error)
}

// RetrieveSMFRegistrationAPIService RetrieveSMFRegistrationAPI service
type RetrieveSMFRegistrationAPIService service

type ApiRetrieveSmfRegistrationRequest struct {
	ctx          context.Context
	ApiService   RetrieveSMFRegistrationAPI
	ueId         string
	pduSessionId int32
}

func (r ApiRetrieveSmfRegistrationRequest) Execute() (*models.SmfRegistration, *http.Response, error) {
	return r.ApiService.RetrieveSmfRegistrationExecute(r)
}

/*
RetrieveSmfRegistration get an SMF registration

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param ueId Identifier of the UE
	@param pduSessionId Identifier of the PDU session
	@return ApiRetrieveSmfRegistrationRequest
*/
func (a *RetrieveSMFRegistrationAPIService) RetrieveSmfRegistration(ctx context.Context, ueId string, pduSessionId int32) ApiRetrieveSmfRegistrationRequest {
	return ApiRetrieveSmfRegistrationRequest{
		ApiService:   a,
		ctx:          ctx,
		ueId:         ueId,
		pduSessionId: pduSessionId,
	}
}

// Execute executes the request
//
//	@return SmfRegistration
func (a *RetrieveSMFRegistrationAPIService) RetrieveSmfRegistrationExecute(r ApiRetrieveSmfRegistrationRequest) (*models.SmfRegistration, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    any
		formFiles           []formFile
		localVarReturnValue *models.SmfRegistration
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RetrieveSMFRegistrationAPIService.RetrieveSmfRegistration")
	if err != nil {
		return localVarReturnValue, nil, &openapi.GenericOpenAPIError{RawError: err.Error()}
	}

	localVarPath := localBasePath + "/{ueId}/registrations/smf-registrations/{pduSessionId}"
	localVarPath = strings.ReplaceAll(localVarPath, "{"+"ueId"+"}", url.PathEscape(openapi.ParameterValueToString(r.ueId, "ueId")))
	localVarPath = strings.ReplaceAll(localVarPath, "{"+"pduSessionId"+"}", url.PathEscape(openapi.ParameterValueToString(r.pduSessionId, "pduSessionId")))

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.pduSessionId < 0 {
		return localVarReturnValue, nil, openapi.ReportError("pduSessionId must be greater than 0")
	}
	if r.pduSessionId > 255 {
		return localVarReturnValue, nil, openapi.ReportError("pduSessionId must be less than 255")
	}

	// set Content-Type header
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := openapi.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := openapi.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
