// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"strings"

	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
)

type NonUEN2MessageNotificationIndividualSubscriptionDocumentAPI interface {

	/*
		NonUeN2InfoUnSubscribe Namf_Communication Non UE N2 Info UnSubscribe service Operation

			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param n2NotifySubscriptionId N2 info Subscription Identifier
			@return ApiNonUeN2InfoUnSubscribeRequest
	*/
	NonUeN2InfoUnSubscribe(ctx context.Context, n2NotifySubscriptionId string) ApiNonUeN2InfoUnSubscribeRequest

	// NonUeN2InfoUnSubscribeExecute executes the request
	NonUeN2InfoUnSubscribeExecute(r ApiNonUeN2InfoUnSubscribeRequest) (*http.Response, error)
}

// NonUEN2MessageNotificationIndividualSubscriptionDocumentAPIService NonUEN2MessageNotificationIndividualSubscriptionDocumentAPI service
type NonUEN2MessageNotificationIndividualSubscriptionDocumentAPIService service

type ApiNonUeN2InfoUnSubscribeRequest struct {
	ctx                    context.Context
	ApiService             NonUEN2MessageNotificationIndividualSubscriptionDocumentAPI
	n2NotifySubscriptionId string
}

func (r ApiNonUeN2InfoUnSubscribeRequest) Execute() (*http.Response, error) {
	return r.ApiService.NonUeN2InfoUnSubscribeExecute(r)
}

/*
NonUeN2InfoUnSubscribe Namf_Communication Non UE N2 Info UnSubscribe service Operation

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param n2NotifySubscriptionId N2 info Subscription Identifier
	@return ApiNonUeN2InfoUnSubscribeRequest
*/
func (a *NonUEN2MessageNotificationIndividualSubscriptionDocumentAPIService) NonUeN2InfoUnSubscribe(ctx context.Context, n2NotifySubscriptionId string) ApiNonUeN2InfoUnSubscribeRequest {
	return ApiNonUeN2InfoUnSubscribeRequest{
		ApiService:             a,
		ctx:                    ctx,
		n2NotifySubscriptionId: n2NotifySubscriptionId,
	}
}

// Execute executes the request
func (a *NonUEN2MessageNotificationIndividualSubscriptionDocumentAPIService) NonUeN2InfoUnSubscribeExecute(r ApiNonUeN2InfoUnSubscribeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   any
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NonUEN2MessageNotificationIndividualSubscriptionDocumentAPIService.NonUeN2InfoUnSubscribe")
	if err != nil {
		return nil, &openapi.GenericOpenAPIError{RawError: err.Error()}
	}

	localVarPath := localBasePath + "/non-ue-n2-messages/subscriptions/{n2NotifySubscriptionId}"
	localVarPath = strings.ReplaceAll(localVarPath, "{"+"n2NotifySubscriptionId"+"}", url.PathEscape(openapi.ParameterValueToString(r.n2NotifySubscriptionId, "n2NotifySubscriptionId")))

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// set Content-Type header
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := openapi.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := openapi.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 307 {
			var v models.RedirectResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 308 {
			var v models.RedirectResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
