// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package Namf_Communication

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"strings"

	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
)

type N1N2IndividualSubscriptionDocumentAPI interface {

	/*
		N1N2MessageUnSubscribe Namf_Communication N1N2 Message UnSubscribe (UE Specific) service Operation

			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param ueContextId UE Context Identifier
			@param subscriptionId Subscription Identifier
			@return ApiN1N2MessageUnSubscribeRequest
	*/
	N1N2MessageUnSubscribe(ctx context.Context, ueContextId string, subscriptionId string) ApiN1N2MessageUnSubscribeRequest

	// N1N2MessageUnSubscribeExecute executes the request
	N1N2MessageUnSubscribeExecute(r ApiN1N2MessageUnSubscribeRequest) (*http.Response, error)
}

// N1N2IndividualSubscriptionDocumentAPIService N1N2IndividualSubscriptionDocumentAPI service
type N1N2IndividualSubscriptionDocumentAPIService service

type ApiN1N2MessageUnSubscribeRequest struct {
	ctx            context.Context
	ApiService     N1N2IndividualSubscriptionDocumentAPI
	ueContextId    string
	subscriptionId string
}

func (r ApiN1N2MessageUnSubscribeRequest) Execute() (*http.Response, error) {
	return r.ApiService.N1N2MessageUnSubscribeExecute(r)
}

/*
N1N2MessageUnSubscribe Namf_Communication N1N2 Message UnSubscribe (UE Specific) service Operation

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param ueContextId UE Context Identifier
	@param subscriptionId Subscription Identifier
	@return ApiN1N2MessageUnSubscribeRequest
*/
func (a *N1N2IndividualSubscriptionDocumentAPIService) N1N2MessageUnSubscribe(ctx context.Context, ueContextId string, subscriptionId string) ApiN1N2MessageUnSubscribeRequest {
	return ApiN1N2MessageUnSubscribeRequest{
		ApiService:     a,
		ctx:            ctx,
		ueContextId:    ueContextId,
		subscriptionId: subscriptionId,
	}
}

// Execute executes the request
func (a *N1N2IndividualSubscriptionDocumentAPIService) N1N2MessageUnSubscribeExecute(r ApiN1N2MessageUnSubscribeRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   any
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "N1N2IndividualSubscriptionDocumentAPIService.N1N2MessageUnSubscribe")
	if err != nil {
		return nil, &openapi.GenericOpenAPIError{RawError: err.Error()}
	}

	localVarPath := localBasePath + "/ue-contexts/{ueContextId}/n1-n2-messages/subscriptions/{subscriptionId}"
	localVarPath = strings.ReplaceAll(localVarPath, "{"+"ueContextId"+"}", url.PathEscape(openapi.ParameterValueToString(r.ueContextId, "ueContextId")))
	localVarPath = strings.ReplaceAll(localVarPath, "{"+"subscriptionId"+"}", url.PathEscape(openapi.ParameterValueToString(r.subscriptionId, "subscriptionId")))

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// set Content-Type header
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}
	localVarHTTPContentType := openapi.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/problem+json"}

	// set Accept header
	localVarHTTPHeaderAccept := openapi.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &openapi.GenericOpenAPIError{
			RawBody:  localVarBody,
			RawError: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 307 {
			var v models.RedirectResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 308 {
			var v models.RedirectResponse
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 411 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 413 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 415 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 429 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 502 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v models.ProblemDetails
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.RawError = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.RawError = openapi.FormatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.RawModel = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
