// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the DnnInfo type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &DnnInfo{}

// DnnInfo struct for DnnInfo
type DnnInfo struct {
	Dnn                 AccessAndMobilitySubscriptionDataSubscribedDnnListInner `json:"dnn" yaml:"dnn"`
	DefaultDnnIndicator *bool                                                   `json:"defaultDnnIndicator,omitempty" yaml:"defaultDnnIndicator,omitempty"`
	LboRoamingAllowed   *bool                                                   `json:"lboRoamingAllowed,omitempty" yaml:"lboRoamingAllowed,omitempty"`
	IwkEpsInd           *bool                                                   `json:"iwkEpsInd,omitempty" yaml:"iwkEpsInd,omitempty"`
	DnnBarred           *bool                                                   `json:"dnnBarred,omitempty" yaml:"dnnBarred,omitempty"`
	InvokeNefInd        *bool                                                   `json:"invokeNefInd,omitempty" yaml:"invokeNefInd,omitempty"`
	SmfList             []string                                                `json:"smfList,omitempty" yaml:"smfList,omitempty"`
	SameSmfInd          *bool                                                   `json:"sameSmfInd,omitempty" yaml:"sameSmfInd,omitempty"`
	HrSboAllowed        *bool                                                   `json:"hrSboAllowed,omitempty" yaml:"hrSboAllowed,omitempty"`
}

// NewDnnInfo instantiates a new DnnInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDnnInfo(dnn AccessAndMobilitySubscriptionDataSubscribedDnnListInner) *DnnInfo {
	this := DnnInfo{}
	this.Dnn = dnn
	var hrSboAllowed bool = false
	this.HrSboAllowed = &hrSboAllowed
	return &this
}

// NewDnnInfoWithDefaults instantiates a new DnnInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDnnInfoWithDefaults() *DnnInfo {
	this := DnnInfo{}
	var hrSboAllowed bool = false
	this.HrSboAllowed = &hrSboAllowed
	return &this
}

// GetDnn returns the Dnn field value
func (o *DnnInfo) GetDnn() AccessAndMobilitySubscriptionDataSubscribedDnnListInner {
	if o == nil {
		var ret AccessAndMobilitySubscriptionDataSubscribedDnnListInner
		return ret
	}

	return o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetDnnOk() (*AccessAndMobilitySubscriptionDataSubscribedDnnListInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dnn, true
}

// SetDnn sets field value
func (o *DnnInfo) SetDnn(v AccessAndMobilitySubscriptionDataSubscribedDnnListInner) {
	o.Dnn = v
}

// GetDefaultDnnIndicator returns the DefaultDnnIndicator field value if set, zero value otherwise.
func (o *DnnInfo) GetDefaultDnnIndicator() bool {
	if o == nil || openapi.IsNil(o.DefaultDnnIndicator) {
		var ret bool
		return ret
	}
	return *o.DefaultDnnIndicator
}

// GetDefaultDnnIndicatorOk returns a tuple with the DefaultDnnIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetDefaultDnnIndicatorOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.DefaultDnnIndicator) {
		return nil, false
	}
	return o.DefaultDnnIndicator, true
}

// HasDefaultDnnIndicator returns a boolean if a field has been set.
func (o *DnnInfo) HasDefaultDnnIndicator() bool {
	if o != nil && !openapi.IsNil(o.DefaultDnnIndicator) {
		return true
	}

	return false
}

// SetDefaultDnnIndicator gets a reference to the given bool and assigns it to the DefaultDnnIndicator field.
func (o *DnnInfo) SetDefaultDnnIndicator(v bool) {
	o.DefaultDnnIndicator = &v
}

// GetLboRoamingAllowed returns the LboRoamingAllowed field value if set, zero value otherwise.
func (o *DnnInfo) GetLboRoamingAllowed() bool {
	if o == nil || openapi.IsNil(o.LboRoamingAllowed) {
		var ret bool
		return ret
	}
	return *o.LboRoamingAllowed
}

// GetLboRoamingAllowedOk returns a tuple with the LboRoamingAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetLboRoamingAllowedOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.LboRoamingAllowed) {
		return nil, false
	}
	return o.LboRoamingAllowed, true
}

// HasLboRoamingAllowed returns a boolean if a field has been set.
func (o *DnnInfo) HasLboRoamingAllowed() bool {
	if o != nil && !openapi.IsNil(o.LboRoamingAllowed) {
		return true
	}

	return false
}

// SetLboRoamingAllowed gets a reference to the given bool and assigns it to the LboRoamingAllowed field.
func (o *DnnInfo) SetLboRoamingAllowed(v bool) {
	o.LboRoamingAllowed = &v
}

// GetIwkEpsInd returns the IwkEpsInd field value if set, zero value otherwise.
func (o *DnnInfo) GetIwkEpsInd() bool {
	if o == nil || openapi.IsNil(o.IwkEpsInd) {
		var ret bool
		return ret
	}
	return *o.IwkEpsInd
}

// GetIwkEpsIndOk returns a tuple with the IwkEpsInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetIwkEpsIndOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.IwkEpsInd) {
		return nil, false
	}
	return o.IwkEpsInd, true
}

// HasIwkEpsInd returns a boolean if a field has been set.
func (o *DnnInfo) HasIwkEpsInd() bool {
	if o != nil && !openapi.IsNil(o.IwkEpsInd) {
		return true
	}

	return false
}

// SetIwkEpsInd gets a reference to the given bool and assigns it to the IwkEpsInd field.
func (o *DnnInfo) SetIwkEpsInd(v bool) {
	o.IwkEpsInd = &v
}

// GetDnnBarred returns the DnnBarred field value if set, zero value otherwise.
func (o *DnnInfo) GetDnnBarred() bool {
	if o == nil || openapi.IsNil(o.DnnBarred) {
		var ret bool
		return ret
	}
	return *o.DnnBarred
}

// GetDnnBarredOk returns a tuple with the DnnBarred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetDnnBarredOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.DnnBarred) {
		return nil, false
	}
	return o.DnnBarred, true
}

// HasDnnBarred returns a boolean if a field has been set.
func (o *DnnInfo) HasDnnBarred() bool {
	if o != nil && !openapi.IsNil(o.DnnBarred) {
		return true
	}

	return false
}

// SetDnnBarred gets a reference to the given bool and assigns it to the DnnBarred field.
func (o *DnnInfo) SetDnnBarred(v bool) {
	o.DnnBarred = &v
}

// GetInvokeNefInd returns the InvokeNefInd field value if set, zero value otherwise.
func (o *DnnInfo) GetInvokeNefInd() bool {
	if o == nil || openapi.IsNil(o.InvokeNefInd) {
		var ret bool
		return ret
	}
	return *o.InvokeNefInd
}

// GetInvokeNefIndOk returns a tuple with the InvokeNefInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetInvokeNefIndOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.InvokeNefInd) {
		return nil, false
	}
	return o.InvokeNefInd, true
}

// HasInvokeNefInd returns a boolean if a field has been set.
func (o *DnnInfo) HasInvokeNefInd() bool {
	if o != nil && !openapi.IsNil(o.InvokeNefInd) {
		return true
	}

	return false
}

// SetInvokeNefInd gets a reference to the given bool and assigns it to the InvokeNefInd field.
func (o *DnnInfo) SetInvokeNefInd(v bool) {
	o.InvokeNefInd = &v
}

// GetSmfList returns the SmfList field value if set, zero value otherwise.
func (o *DnnInfo) GetSmfList() []string {
	if o == nil || openapi.IsNil(o.SmfList) {
		var ret []string
		return ret
	}
	return o.SmfList
}

// GetSmfListOk returns a tuple with the SmfList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetSmfListOk() ([]string, bool) {
	if o == nil || openapi.IsNil(o.SmfList) {
		return nil, false
	}
	return o.SmfList, true
}

// HasSmfList returns a boolean if a field has been set.
func (o *DnnInfo) HasSmfList() bool {
	if o != nil && !openapi.IsNil(o.SmfList) {
		return true
	}

	return false
}

// SetSmfList gets a reference to the given []string and assigns it to the SmfList field.
func (o *DnnInfo) SetSmfList(v []string) {
	o.SmfList = v
}

// GetSameSmfInd returns the SameSmfInd field value if set, zero value otherwise.
func (o *DnnInfo) GetSameSmfInd() bool {
	if o == nil || openapi.IsNil(o.SameSmfInd) {
		var ret bool
		return ret
	}
	return *o.SameSmfInd
}

// GetSameSmfIndOk returns a tuple with the SameSmfInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetSameSmfIndOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.SameSmfInd) {
		return nil, false
	}
	return o.SameSmfInd, true
}

// HasSameSmfInd returns a boolean if a field has been set.
func (o *DnnInfo) HasSameSmfInd() bool {
	if o != nil && !openapi.IsNil(o.SameSmfInd) {
		return true
	}

	return false
}

// SetSameSmfInd gets a reference to the given bool and assigns it to the SameSmfInd field.
func (o *DnnInfo) SetSameSmfInd(v bool) {
	o.SameSmfInd = &v
}

// GetHrSboAllowed returns the HrSboAllowed field value if set, zero value otherwise.
func (o *DnnInfo) GetHrSboAllowed() bool {
	if o == nil || openapi.IsNil(o.HrSboAllowed) {
		var ret bool
		return ret
	}
	return *o.HrSboAllowed
}

// GetHrSboAllowedOk returns a tuple with the HrSboAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DnnInfo) GetHrSboAllowedOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.HrSboAllowed) {
		return nil, false
	}
	return o.HrSboAllowed, true
}

// HasHrSboAllowed returns a boolean if a field has been set.
func (o *DnnInfo) HasHrSboAllowed() bool {
	if o != nil && !openapi.IsNil(o.HrSboAllowed) {
		return true
	}

	return false
}

// SetHrSboAllowed gets a reference to the given bool and assigns it to the HrSboAllowed field.
func (o *DnnInfo) SetHrSboAllowed(v bool) {
	o.HrSboAllowed = &v
}

func (o DnnInfo) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	toSerialize["dnn"] = o.Dnn
	if !openapi.IsNil(o.DefaultDnnIndicator) {
		toSerialize["defaultDnnIndicator"] = o.DefaultDnnIndicator
	}
	if !openapi.IsNil(o.LboRoamingAllowed) {
		toSerialize["lboRoamingAllowed"] = o.LboRoamingAllowed
	}
	if !openapi.IsNil(o.IwkEpsInd) {
		toSerialize["iwkEpsInd"] = o.IwkEpsInd
	}
	if !openapi.IsNil(o.DnnBarred) {
		toSerialize["dnnBarred"] = o.DnnBarred
	}
	if !openapi.IsNil(o.InvokeNefInd) {
		toSerialize["invokeNefInd"] = o.InvokeNefInd
	}
	if !openapi.IsNil(o.SmfList) {
		toSerialize["smfList"] = o.SmfList
	}
	if !openapi.IsNil(o.SameSmfInd) {
		toSerialize["sameSmfInd"] = o.SameSmfInd
	}
	if !openapi.IsNil(o.HrSboAllowed) {
		toSerialize["hrSboAllowed"] = o.HrSboAllowed
	}
	return toSerialize, nil
}

type NullableDnnInfo struct {
	value *DnnInfo
	isSet bool
}

func (v NullableDnnInfo) Get() *DnnInfo {
	return v.value
}

func (v *NullableDnnInfo) Set(val *DnnInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDnnInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDnnInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDnnInfo(val *DnnInfo) *NullableDnnInfo {
	return &NullableDnnInfo{value: val, isSet: true}
}

func (v NullableDnnInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDnnInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
