// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// SmfChangeIndication Indicates the I-SMF or V-SMF change or removal
type SmfChangeIndication string

// List of SmfChangeIndication
const (
	SMFCHANGEINDICATION_CHANGED SmfChangeIndication = "CHANGED"
	SMFCHANGEINDICATION_REMOVED SmfChangeIndication = "REMOVED"
)

// All allowed values of SmfChangeIndication enum
var AllowedSmfChangeIndicationEnumValues = []SmfChangeIndication{
	"CHANGED",
	"REMOVED",
}

func (v *SmfChangeIndication) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SmfChangeIndication(value)
	if slices.Contains(AllowedSmfChangeIndicationEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid SmfChangeIndication", value)
}

// NewSmfChangeIndicationFromValue returns a pointer to a valid SmfChangeIndication
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSmfChangeIndicationFromValue(v string) (*SmfChangeIndication, error) {
	ev := SmfChangeIndication(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for SmfChangeIndication: valid values are %v", v, AllowedSmfChangeIndicationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SmfChangeIndication) IsValid() bool {
	return slices.Contains(AllowedSmfChangeIndicationEnumValues, v)
}

// Ptr returns reference to SmfChangeIndication value
func (v SmfChangeIndication) Ptr() *SmfChangeIndication {
	return &v
}

type NullableSmfChangeIndication struct {
	value *SmfChangeIndication
	isSet bool
}

func (v NullableSmfChangeIndication) Get() *SmfChangeIndication {
	return v.value
}

func (v *NullableSmfChangeIndication) Set(val *SmfChangeIndication) {
	v.value = val
	v.isSet = true
}

func (v NullableSmfChangeIndication) IsSet() bool {
	return v.isSet
}

func (v *NullableSmfChangeIndication) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmfChangeIndication(val *SmfChangeIndication) *NullableSmfChangeIndication {
	return &NullableSmfChangeIndication{value: val, isSet: true}
}

func (v NullableSmfChangeIndication) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmfChangeIndication) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
