// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// RedirectAddressType Indicates the redirect address type.   Possible values are - IPV4_ADDR: Indicates that the address type is in the form of \"dotted-decimal\" IPv4 address. - IPV6_ADDR: Indicates that the address type is in the form of IPv6 address. - URL: Indicates that the address type is in the form of Uniform Resource Locator. - SIP_URI: Indicates that the address type is in the form of SIP Uniform Resource Identifier.
type RedirectAddressType string

// List of RedirectAddressType
const (
	REDIRECTADDRESSTYPE_IPV4_ADDR RedirectAddressType = "IPV4_ADDR"
	REDIRECTADDRESSTYPE_IPV6_ADDR RedirectAddressType = "IPV6_ADDR"
	REDIRECTADDRESSTYPE_URL       RedirectAddressType = "URL"
	REDIRECTADDRESSTYPE_SIP_URI   RedirectAddressType = "SIP_URI"
)

// All allowed values of RedirectAddressType enum
var AllowedRedirectAddressTypeEnumValues = []RedirectAddressType{
	"IPV4_ADDR",
	"IPV6_ADDR",
	"URL",
	"SIP_URI",
}

func (v *RedirectAddressType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RedirectAddressType(value)
	if slices.Contains(AllowedRedirectAddressTypeEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid RedirectAddressType", value)
}

// NewRedirectAddressTypeFromValue returns a pointer to a valid RedirectAddressType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRedirectAddressTypeFromValue(v string) (*RedirectAddressType, error) {
	ev := RedirectAddressType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for RedirectAddressType: valid values are %v", v, AllowedRedirectAddressTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RedirectAddressType) IsValid() bool {
	return slices.Contains(AllowedRedirectAddressTypeEnumValues, v)
}

// Ptr returns reference to RedirectAddressType value
func (v RedirectAddressType) Ptr() *RedirectAddressType {
	return &v
}

type NullableRedirectAddressType struct {
	value *RedirectAddressType
	isSet bool
}

func (v NullableRedirectAddressType) Get() *RedirectAddressType {
	return v.value
}

func (v *NullableRedirectAddressType) Set(val *RedirectAddressType) {
	v.value = val
	v.isSet = true
}

func (v NullableRedirectAddressType) IsSet() bool {
	return v.isSet
}

func (v *NullableRedirectAddressType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedirectAddressType(val *RedirectAddressType) *NullableRedirectAddressType {
	return &NullableRedirectAddressType{value: val, isSet: true}
}

func (v NullableRedirectAddressType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedirectAddressType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
