// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Location

AMF Location Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the HighAccuracyGnssMetrics type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &HighAccuracyGnssMetrics{}

// HighAccuracyGnssMetrics High Accuracy GNSS Positioning Metrics.
type HighAccuracyGnssMetrics struct {
	NrOfUsedSatellites *int32   `json:"nrOfUsedSatellites,omitempty" yaml:"nrOfUsedSatellites,omitempty"`
	Hdopi              *int32   `json:"hdopi,omitempty" yaml:"hdopi,omitempty"`
	Pdopi              *int32   `json:"pdopi,omitempty" yaml:"pdopi,omitempty"`
	Age                *int32   `json:"age,omitempty" yaml:"age,omitempty"`
	FixType            *FixType `json:"fixType,omitempty" yaml:"fixType,omitempty"`
}

// NewHighAccuracyGnssMetrics instantiates a new HighAccuracyGnssMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHighAccuracyGnssMetrics() *HighAccuracyGnssMetrics {
	this := HighAccuracyGnssMetrics{}
	return &this
}

// NewHighAccuracyGnssMetricsWithDefaults instantiates a new HighAccuracyGnssMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHighAccuracyGnssMetricsWithDefaults() *HighAccuracyGnssMetrics {
	this := HighAccuracyGnssMetrics{}
	return &this
}

// GetNrOfUsedSatellites returns the NrOfUsedSatellites field value if set, zero value otherwise.
func (o *HighAccuracyGnssMetrics) GetNrOfUsedSatellites() int32 {
	if o == nil || openapi.IsNil(o.NrOfUsedSatellites) {
		var ret int32
		return ret
	}
	return *o.NrOfUsedSatellites
}

// GetNrOfUsedSatellitesOk returns a tuple with the NrOfUsedSatellites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighAccuracyGnssMetrics) GetNrOfUsedSatellitesOk() (*int32, bool) {
	if o == nil || openapi.IsNil(o.NrOfUsedSatellites) {
		return nil, false
	}
	return o.NrOfUsedSatellites, true
}

// HasNrOfUsedSatellites returns a boolean if a field has been set.
func (o *HighAccuracyGnssMetrics) HasNrOfUsedSatellites() bool {
	if o != nil && !openapi.IsNil(o.NrOfUsedSatellites) {
		return true
	}

	return false
}

// SetNrOfUsedSatellites gets a reference to the given int32 and assigns it to the NrOfUsedSatellites field.
func (o *HighAccuracyGnssMetrics) SetNrOfUsedSatellites(v int32) {
	o.NrOfUsedSatellites = &v
}

// GetHdopi returns the Hdopi field value if set, zero value otherwise.
func (o *HighAccuracyGnssMetrics) GetHdopi() int32 {
	if o == nil || openapi.IsNil(o.Hdopi) {
		var ret int32
		return ret
	}
	return *o.Hdopi
}

// GetHdopiOk returns a tuple with the Hdopi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighAccuracyGnssMetrics) GetHdopiOk() (*int32, bool) {
	if o == nil || openapi.IsNil(o.Hdopi) {
		return nil, false
	}
	return o.Hdopi, true
}

// HasHdopi returns a boolean if a field has been set.
func (o *HighAccuracyGnssMetrics) HasHdopi() bool {
	if o != nil && !openapi.IsNil(o.Hdopi) {
		return true
	}

	return false
}

// SetHdopi gets a reference to the given int32 and assigns it to the Hdopi field.
func (o *HighAccuracyGnssMetrics) SetHdopi(v int32) {
	o.Hdopi = &v
}

// GetPdopi returns the Pdopi field value if set, zero value otherwise.
func (o *HighAccuracyGnssMetrics) GetPdopi() int32 {
	if o == nil || openapi.IsNil(o.Pdopi) {
		var ret int32
		return ret
	}
	return *o.Pdopi
}

// GetPdopiOk returns a tuple with the Pdopi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighAccuracyGnssMetrics) GetPdopiOk() (*int32, bool) {
	if o == nil || openapi.IsNil(o.Pdopi) {
		return nil, false
	}
	return o.Pdopi, true
}

// HasPdopi returns a boolean if a field has been set.
func (o *HighAccuracyGnssMetrics) HasPdopi() bool {
	if o != nil && !openapi.IsNil(o.Pdopi) {
		return true
	}

	return false
}

// SetPdopi gets a reference to the given int32 and assigns it to the Pdopi field.
func (o *HighAccuracyGnssMetrics) SetPdopi(v int32) {
	o.Pdopi = &v
}

// GetAge returns the Age field value if set, zero value otherwise.
func (o *HighAccuracyGnssMetrics) GetAge() int32 {
	if o == nil || openapi.IsNil(o.Age) {
		var ret int32
		return ret
	}
	return *o.Age
}

// GetAgeOk returns a tuple with the Age field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighAccuracyGnssMetrics) GetAgeOk() (*int32, bool) {
	if o == nil || openapi.IsNil(o.Age) {
		return nil, false
	}
	return o.Age, true
}

// HasAge returns a boolean if a field has been set.
func (o *HighAccuracyGnssMetrics) HasAge() bool {
	if o != nil && !openapi.IsNil(o.Age) {
		return true
	}

	return false
}

// SetAge gets a reference to the given int32 and assigns it to the Age field.
func (o *HighAccuracyGnssMetrics) SetAge(v int32) {
	o.Age = &v
}

// GetFixType returns the FixType field value if set, zero value otherwise.
func (o *HighAccuracyGnssMetrics) GetFixType() FixType {
	if o == nil || openapi.IsNil(o.FixType) {
		var ret FixType
		return ret
	}
	return *o.FixType
}

// GetFixTypeOk returns a tuple with the FixType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HighAccuracyGnssMetrics) GetFixTypeOk() (*FixType, bool) {
	if o == nil || openapi.IsNil(o.FixType) {
		return nil, false
	}
	return o.FixType, true
}

// HasFixType returns a boolean if a field has been set.
func (o *HighAccuracyGnssMetrics) HasFixType() bool {
	if o != nil && !openapi.IsNil(o.FixType) {
		return true
	}

	return false
}

// SetFixType gets a reference to the given FixType and assigns it to the FixType field.
func (o *HighAccuracyGnssMetrics) SetFixType(v FixType) {
	o.FixType = &v
}

func (o HighAccuracyGnssMetrics) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.NrOfUsedSatellites) {
		toSerialize["nrOfUsedSatellites"] = o.NrOfUsedSatellites
	}
	if !openapi.IsNil(o.Hdopi) {
		toSerialize["hdopi"] = o.Hdopi
	}
	if !openapi.IsNil(o.Pdopi) {
		toSerialize["pdopi"] = o.Pdopi
	}
	if !openapi.IsNil(o.Age) {
		toSerialize["age"] = o.Age
	}
	if !openapi.IsNil(o.FixType) {
		toSerialize["fixType"] = o.FixType
	}
	return toSerialize, nil
}

type NullableHighAccuracyGnssMetrics struct {
	value *HighAccuracyGnssMetrics
	isSet bool
}

func (v NullableHighAccuracyGnssMetrics) Get() *HighAccuracyGnssMetrics {
	return v.value
}

func (v *NullableHighAccuracyGnssMetrics) Set(val *HighAccuracyGnssMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableHighAccuracyGnssMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableHighAccuracyGnssMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHighAccuracyGnssMetrics(val *HighAccuracyGnssMetrics) *NullableHighAccuracyGnssMetrics {
	return &NullableHighAccuracyGnssMetrics{value: val, isSet: true}
}

func (v NullableHighAccuracyGnssMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHighAccuracyGnssMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
