// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// ClockQualityDetailLevel Indicates the Clock Quality Detail Level.
type ClockQualityDetailLevel string

// List of ClockQualityDetailLevel
const (
	CLOCKQUALITYDETAILLEVEL_CLOCK_QUALITY_METRICS ClockQualityDetailLevel = "CLOCK_QUALITY_METRICS"
	CLOCKQUALITYDETAILLEVEL_ACCEPT_INDICATION     ClockQualityDetailLevel = "ACCEPT_INDICATION"
)

// All allowed values of ClockQualityDetailLevel enum
var AllowedClockQualityDetailLevelEnumValues = []ClockQualityDetailLevel{
	"CLOCK_QUALITY_METRICS",
	"ACCEPT_INDICATION",
}

func (v *ClockQualityDetailLevel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ClockQualityDetailLevel(value)
	if slices.Contains(AllowedClockQualityDetailLevelEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid ClockQualityDetailLevel", value)
}

// NewClockQualityDetailLevelFromValue returns a pointer to a valid ClockQualityDetailLevel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewClockQualityDetailLevelFromValue(v string) (*ClockQualityDetailLevel, error) {
	ev := ClockQualityDetailLevel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for ClockQualityDetailLevel: valid values are %v", v, AllowedClockQualityDetailLevelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ClockQualityDetailLevel) IsValid() bool {
	return slices.Contains(AllowedClockQualityDetailLevelEnumValues, v)
}

// Ptr returns reference to ClockQualityDetailLevel value
func (v ClockQualityDetailLevel) Ptr() *ClockQualityDetailLevel {
	return &v
}

type NullableClockQualityDetailLevel struct {
	value *ClockQualityDetailLevel
	isSet bool
}

func (v NullableClockQualityDetailLevel) Get() *ClockQualityDetailLevel {
	return v.value
}

func (v *NullableClockQualityDetailLevel) Set(val *ClockQualityDetailLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableClockQualityDetailLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableClockQualityDetailLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClockQualityDetailLevel(val *ClockQualityDetailLevel) *NullableClockQualityDetailLevel {
	return &NullableClockQualityDetailLevel{value: val, isSet: true}
}

func (v NullableClockQualityDetailLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClockQualityDetailLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
