// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_SMPolicyControl API

Session Management Policy Control Service
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the SliceUsgCtrlInfoSm type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &SliceUsgCtrlInfoSm{}

// SliceUsgCtrlInfoSm Represents network slice usage control information.
type SliceUsgCtrlInfoSm struct {
	// indicating a time in seconds with OpenAPI defined 'nullable: true' property.
	PduSessInactivTimer openapi.NullableInt32
}

// NewSliceUsgCtrlInfoSm instantiates a new SliceUsgCtrlInfoSm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSliceUsgCtrlInfoSm() *SliceUsgCtrlInfoSm {
	this := SliceUsgCtrlInfoSm{}
	return &this
}

// NewSliceUsgCtrlInfoSmWithDefaults instantiates a new SliceUsgCtrlInfoSm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSliceUsgCtrlInfoSmWithDefaults() *SliceUsgCtrlInfoSm {
	this := SliceUsgCtrlInfoSm{}
	return &this
}

// GetPduSessInactivTimer returns the PduSessInactivTimer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SliceUsgCtrlInfoSm) GetPduSessInactivTimer() int32 {
	if o == nil || openapi.IsNil(o.PduSessInactivTimer.Get()) {
		var ret int32
		return ret
	}
	return *o.PduSessInactivTimer.Get()
}

// GetPduSessInactivTimerOk returns a tuple with the PduSessInactivTimer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SliceUsgCtrlInfoSm) GetPduSessInactivTimerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PduSessInactivTimer.Get(), o.PduSessInactivTimer.IsSet()
}

// HasPduSessInactivTimer returns a boolean if a field has been set.
func (o *SliceUsgCtrlInfoSm) HasPduSessInactivTimer() bool {
	if o != nil && o.PduSessInactivTimer.IsSet() {
		return true
	}

	return false
}

// SetPduSessInactivTimer gets a reference to the given openapi.NullableInt32 and assigns it to the PduSessInactivTimer field.
func (o *SliceUsgCtrlInfoSm) SetPduSessInactivTimer(v int32) {
	o.PduSessInactivTimer.Set(&v)
}

// SetPduSessInactivTimerNil sets the value for PduSessInactivTimer to be an explicit nil
func (o *SliceUsgCtrlInfoSm) SetPduSessInactivTimerNil() {
	o.PduSessInactivTimer.Set(nil)
}

// UnsetPduSessInactivTimer ensures that no value is present for PduSessInactivTimer, not even an explicit nil
func (o *SliceUsgCtrlInfoSm) UnsetPduSessInactivTimer() {
	o.PduSessInactivTimer.Unset()
}

func (o SliceUsgCtrlInfoSm) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if o.PduSessInactivTimer.IsSet() {
		toSerialize["pduSessInactivTimer"] = o.PduSessInactivTimer.Get()
	}
	return toSerialize, nil
}

type NullableSliceUsgCtrlInfoSm struct {
	value *SliceUsgCtrlInfoSm
	isSet bool
}

func (v NullableSliceUsgCtrlInfoSm) Get() *SliceUsgCtrlInfoSm {
	return v.value
}

func (v *NullableSliceUsgCtrlInfoSm) Set(val *SliceUsgCtrlInfoSm) {
	v.value = val
	v.isSet = true
}

func (v NullableSliceUsgCtrlInfoSm) IsSet() bool {
	return v.isSet
}

func (v *NullableSliceUsgCtrlInfoSm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSliceUsgCtrlInfoSm(val *SliceUsgCtrlInfoSm) *NullableSliceUsgCtrlInfoSm {
	return &NullableSliceUsgCtrlInfoSm{value: val, isSet: true}
}

func (v NullableSliceUsgCtrlInfoSm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSliceUsgCtrlInfoSm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
