// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_EventExposure

AMF Event Exposure Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.5

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the SupportedSnssai type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &SupportedSnssai{}

// SupportedSnssai Supported S-NSSAIs
type SupportedSnssai struct {
	SNssai         Snssai `json:"sNssai" yaml:"sNssai"`
	RestrictionInd *bool  `json:"restrictionInd,omitempty" yaml:"restrictionInd,omitempty"`
}

// NewSupportedSnssai instantiates a new SupportedSnssai object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupportedSnssai(sNssai Snssai) *SupportedSnssai {
	this := SupportedSnssai{}
	this.SNssai = sNssai
	var restrictionInd bool = false
	this.RestrictionInd = &restrictionInd
	return &this
}

// NewSupportedSnssaiWithDefaults instantiates a new SupportedSnssai object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSupportedSnssaiWithDefaults() *SupportedSnssai {
	this := SupportedSnssai{}
	var restrictionInd bool = false
	this.RestrictionInd = &restrictionInd
	return &this
}

// GetSNssai returns the SNssai field value
func (o *SupportedSnssai) GetSNssai() Snssai {
	if o == nil {
		var ret Snssai
		return ret
	}

	return o.SNssai
}

// GetSNssaiOk returns a tuple with the SNssai field value
// and a boolean to check if the value has been set.
func (o *SupportedSnssai) GetSNssaiOk() (*Snssai, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SNssai, true
}

// SetSNssai sets field value
func (o *SupportedSnssai) SetSNssai(v Snssai) {
	o.SNssai = v
}

// GetRestrictionInd returns the RestrictionInd field value if set, zero value otherwise.
func (o *SupportedSnssai) GetRestrictionInd() bool {
	if o == nil || openapi.IsNil(o.RestrictionInd) {
		var ret bool
		return ret
	}
	return *o.RestrictionInd
}

// GetRestrictionIndOk returns a tuple with the RestrictionInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SupportedSnssai) GetRestrictionIndOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.RestrictionInd) {
		return nil, false
	}
	return o.RestrictionInd, true
}

// HasRestrictionInd returns a boolean if a field has been set.
func (o *SupportedSnssai) HasRestrictionInd() bool {
	if o != nil && !openapi.IsNil(o.RestrictionInd) {
		return true
	}

	return false
}

// SetRestrictionInd gets a reference to the given bool and assigns it to the RestrictionInd field.
func (o *SupportedSnssai) SetRestrictionInd(v bool) {
	o.RestrictionInd = &v
}

func (o SupportedSnssai) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	toSerialize["sNssai"] = o.SNssai
	if !openapi.IsNil(o.RestrictionInd) {
		toSerialize["restrictionInd"] = o.RestrictionInd
	}
	return toSerialize, nil
}

type NullableSupportedSnssai struct {
	value *SupportedSnssai
	isSet bool
}

func (v NullableSupportedSnssai) Get() *SupportedSnssai {
	return v.value
}

func (v *NullableSupportedSnssai) Set(val *SupportedSnssai) {
	v.value = val
	v.isSet = true
}

func (v NullableSupportedSnssai) IsSet() bool {
	return v.isSet
}

func (v *NullableSupportedSnssai) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupportedSnssai(val *SupportedSnssai) *NullableSupportedSnssai {
	return &NullableSupportedSnssai{value: val, isSet: true}
}

func (v NullableSupportedSnssai) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupportedSnssai) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
