// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// PositioningMethodMdt The enumeration LoggingDurationMdt defines Logging Duration for MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.13-1.
type PositioningMethodMdt string

// List of PositioningMethodMdt
const (
	POSITIONINGMETHODMDT_GNSS      PositioningMethodMdt = "GNSS"
	POSITIONINGMETHODMDT_E_CELL_ID PositioningMethodMdt = "E_CELL_ID"
)

// All allowed values of PositioningMethodMdt enum
var AllowedPositioningMethodMdtEnumValues = []PositioningMethodMdt{
	"GNSS",
	"E_CELL_ID",
}

func (v *PositioningMethodMdt) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PositioningMethodMdt(value)
	if slices.Contains(AllowedPositioningMethodMdtEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid PositioningMethodMdt", value)
}

// NewPositioningMethodMdtFromValue returns a pointer to a valid PositioningMethodMdt
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPositioningMethodMdtFromValue(v string) (*PositioningMethodMdt, error) {
	ev := PositioningMethodMdt(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for PositioningMethodMdt: valid values are %v", v, AllowedPositioningMethodMdtEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PositioningMethodMdt) IsValid() bool {
	return slices.Contains(AllowedPositioningMethodMdtEnumValues, v)
}

// Ptr returns reference to PositioningMethodMdt value
func (v PositioningMethodMdt) Ptr() *PositioningMethodMdt {
	return &v
}

type NullablePositioningMethodMdt struct {
	value *PositioningMethodMdt
	isSet bool
}

func (v NullablePositioningMethodMdt) Get() *PositioningMethodMdt {
	return v.value
}

func (v *NullablePositioningMethodMdt) Set(val *PositioningMethodMdt) {
	v.value = val
	v.isSet = true
}

func (v NullablePositioningMethodMdt) IsSet() bool {
	return v.isSet
}

func (v *NullablePositioningMethodMdt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePositioningMethodMdt(val *PositioningMethodMdt) *NullablePositioningMethodMdt {
	return &NullablePositioningMethodMdt{value: val, isSet: true}
}

func (v NullablePositioningMethodMdt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePositioningMethodMdt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
