// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Location

AMF Location Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"time"

	"github.com/omec-project/openapi/v2"
)

// checks if the ProvidePosInfo type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &ProvidePosInfo{}

// ProvidePosInfo Data within Provide Positioning Information Response
type ProvidePosInfo struct {
	LocationEstimate            *GeographicArea              `json:"locationEstimate,omitempty" yaml:"locationEstimate,omitempty"`
	AccuracyFulfilmentIndicator *AccuracyFulfilmentIndicator `json:"accuracyFulfilmentIndicator,omitempty" yaml:"accuracyFulfilmentIndicator,omitempty"`
	// Indicates value of the age of the location estimate.
	AgeOfLocationEstimate *int32 `json:"ageOfLocationEstimate,omitempty" yaml:"ageOfLocationEstimate,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	TimestampOfLocationEstimate *time.Time                      `json:"timestampOfLocationEstimate,omitempty" yaml:"timestampOfLocationEstimate,omitempty"`
	VelocityEstimate            *VelocityEstimate               `json:"velocityEstimate,omitempty" yaml:"velocityEstimate,omitempty"`
	PositioningDataList         []PositioningMethodAndUsage     `json:"positioningDataList,omitempty" yaml:"positioningDataList,omitempty"`
	GnssPositioningDataList     []GnssPositioningMethodAndUsage `json:"gnssPositioningDataList,omitempty" yaml:"gnssPositioningDataList,omitempty"`
	Ecgi                        *Ecgi                           `json:"ecgi,omitempty" yaml:"ecgi,omitempty"`
	Ncgi                        *Ncgi                           `json:"ncgi,omitempty" yaml:"ncgi,omitempty"`
	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.
	TargetServingNode *string `json:"targetServingNode,omitempty" yaml:"targetServingNode,omitempty"`
	// Fully Qualified Domain Name
	TargetMmeName *string `json:"targetMmeName,omitempty" yaml:"targetMmeName,omitempty" validate:"regexp=^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\\\.)+[A-Za-z]{2,63}\\\\.?$"`
	// Fully Qualified Domain Name
	TargetMmeRealm *string       `json:"targetMmeRealm,omitempty" yaml:"targetMmeRealm,omitempty" validate:"regexp=^([0-9A-Za-z]([-0-9A-Za-z]{0,61}[0-9A-Za-z])?\\\\.)+[A-Za-z]{2,63}\\\\.?$"`
	UtranSrvccInd  *bool         `json:"utranSrvccInd,omitempty" yaml:"utranSrvccInd,omitempty"`
	CivicAddress   *CivicAddress `json:"civicAddress,omitempty" yaml:"civicAddress,omitempty"`
	// Specifies the measured uncompensated atmospheric pressure.
	BarometricPressure *int32 `json:"barometricPressure,omitempty" yaml:"barometricPressure,omitempty"`
	// Indicates value of altitude.
	Altitude *float64 `json:"altitude,omitempty" yaml:"altitude,omitempty"`
	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported.
	SupportedFeatures *string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures,omitempty" validate:"regexp=^[A-Fa-f0-9]*$"`
	// LMF identification.
	ServingLMFIdentification  *string                   `json:"servingLMFIdentification,omitempty" yaml:"servingLMFIdentification,omitempty"`
	LocationPrivacyVerResult  *LocationPrivacyVerResult `json:"locationPrivacyVerResult,omitempty" yaml:"locationPrivacyVerResult,omitempty"`
	AchievedQos               *MinorLocationQoS         `json:"achievedQos,omitempty" yaml:"achievedQos,omitempty"`
	DirectReportInd           *bool                     `json:"directReportInd,omitempty" yaml:"directReportInd,omitempty"`
	AcceptedPeriodicEventInfo *PeriodicEventInfo        `json:"acceptedPeriodicEventInfo,omitempty" yaml:"acceptedPeriodicEventInfo,omitempty"`
	HaGnssMetrics             *HighAccuracyGnssMetrics  `json:"haGnssMetrics,omitempty" yaml:"haGnssMetrics,omitempty"`
	IndoorOutdoorInd          *IndoorOutdoorInd         `json:"indoorOutdoorInd,omitempty" yaml:"indoorOutdoorInd,omitempty"`
	LosNlosMeasureInd         *LosNlosMeasureInd        `json:"losNlosMeasureInd,omitempty" yaml:"losNlosMeasureInd,omitempty"`
	// String identifying an UE with application layer ID. The format of the application  layer ID parameter is same as the Application layer ID defined in clause 11.3.4 of  3GPP TS 24.554.
	RelatedApplicationlayerId *string                 `json:"relatedApplicationlayerId,omitempty" yaml:"relatedApplicationlayerId,omitempty"`
	DistanceDirection         *RangeDirection         `json:"distanceDirection,omitempty" yaml:"distanceDirection,omitempty"`
	Var2dRelativeLocation     *TwoDRelativeLocation   `json:"2dRelativeLocation,omitempty" yaml:"2dRelativeLocation,omitempty"`
	Var3dRelativeLocation     *ThreeDRelativeLocation `json:"3dRelativeLocation,omitempty" yaml:"3dRelativeLocation,omitempty"`
	RelativeVelocity          *VelocityEstimate       `json:"relativeVelocity,omitempty" yaml:"relativeVelocity,omitempty"`
}

// NewProvidePosInfo instantiates a new ProvidePosInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProvidePosInfo() *ProvidePosInfo {
	this := ProvidePosInfo{}
	var directReportInd bool = false
	this.DirectReportInd = &directReportInd
	return &this
}

// NewProvidePosInfoWithDefaults instantiates a new ProvidePosInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProvidePosInfoWithDefaults() *ProvidePosInfo {
	this := ProvidePosInfo{}
	var directReportInd bool = false
	this.DirectReportInd = &directReportInd
	return &this
}

// GetLocationEstimate returns the LocationEstimate field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetLocationEstimate() GeographicArea {
	if o == nil || openapi.IsNil(o.LocationEstimate) {
		var ret GeographicArea
		return ret
	}
	return *o.LocationEstimate
}

// GetLocationEstimateOk returns a tuple with the LocationEstimate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetLocationEstimateOk() (*GeographicArea, bool) {
	if o == nil || openapi.IsNil(o.LocationEstimate) {
		return nil, false
	}
	return o.LocationEstimate, true
}

// HasLocationEstimate returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasLocationEstimate() bool {
	if o != nil && !openapi.IsNil(o.LocationEstimate) {
		return true
	}

	return false
}

// SetLocationEstimate gets a reference to the given GeographicArea and assigns it to the LocationEstimate field.
func (o *ProvidePosInfo) SetLocationEstimate(v GeographicArea) {
	o.LocationEstimate = &v
}

// GetAccuracyFulfilmentIndicator returns the AccuracyFulfilmentIndicator field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetAccuracyFulfilmentIndicator() AccuracyFulfilmentIndicator {
	if o == nil || openapi.IsNil(o.AccuracyFulfilmentIndicator) {
		var ret AccuracyFulfilmentIndicator
		return ret
	}
	return *o.AccuracyFulfilmentIndicator
}

// GetAccuracyFulfilmentIndicatorOk returns a tuple with the AccuracyFulfilmentIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetAccuracyFulfilmentIndicatorOk() (*AccuracyFulfilmentIndicator, bool) {
	if o == nil || openapi.IsNil(o.AccuracyFulfilmentIndicator) {
		return nil, false
	}
	return o.AccuracyFulfilmentIndicator, true
}

// HasAccuracyFulfilmentIndicator returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasAccuracyFulfilmentIndicator() bool {
	if o != nil && !openapi.IsNil(o.AccuracyFulfilmentIndicator) {
		return true
	}

	return false
}

// SetAccuracyFulfilmentIndicator gets a reference to the given AccuracyFulfilmentIndicator and assigns it to the AccuracyFulfilmentIndicator field.
func (o *ProvidePosInfo) SetAccuracyFulfilmentIndicator(v AccuracyFulfilmentIndicator) {
	o.AccuracyFulfilmentIndicator = &v
}

// GetAgeOfLocationEstimate returns the AgeOfLocationEstimate field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetAgeOfLocationEstimate() int32 {
	if o == nil || openapi.IsNil(o.AgeOfLocationEstimate) {
		var ret int32
		return ret
	}
	return *o.AgeOfLocationEstimate
}

// GetAgeOfLocationEstimateOk returns a tuple with the AgeOfLocationEstimate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetAgeOfLocationEstimateOk() (*int32, bool) {
	if o == nil || openapi.IsNil(o.AgeOfLocationEstimate) {
		return nil, false
	}
	return o.AgeOfLocationEstimate, true
}

// HasAgeOfLocationEstimate returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasAgeOfLocationEstimate() bool {
	if o != nil && !openapi.IsNil(o.AgeOfLocationEstimate) {
		return true
	}

	return false
}

// SetAgeOfLocationEstimate gets a reference to the given int32 and assigns it to the AgeOfLocationEstimate field.
func (o *ProvidePosInfo) SetAgeOfLocationEstimate(v int32) {
	o.AgeOfLocationEstimate = &v
}

// GetTimestampOfLocationEstimate returns the TimestampOfLocationEstimate field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetTimestampOfLocationEstimate() time.Time {
	if o == nil || openapi.IsNil(o.TimestampOfLocationEstimate) {
		var ret time.Time
		return ret
	}
	return *o.TimestampOfLocationEstimate
}

// GetTimestampOfLocationEstimateOk returns a tuple with the TimestampOfLocationEstimate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetTimestampOfLocationEstimateOk() (*time.Time, bool) {
	if o == nil || openapi.IsNil(o.TimestampOfLocationEstimate) {
		return nil, false
	}
	return o.TimestampOfLocationEstimate, true
}

// HasTimestampOfLocationEstimate returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasTimestampOfLocationEstimate() bool {
	if o != nil && !openapi.IsNil(o.TimestampOfLocationEstimate) {
		return true
	}

	return false
}

// SetTimestampOfLocationEstimate gets a reference to the given time.Time and assigns it to the TimestampOfLocationEstimate field.
func (o *ProvidePosInfo) SetTimestampOfLocationEstimate(v time.Time) {
	o.TimestampOfLocationEstimate = &v
}

// GetVelocityEstimate returns the VelocityEstimate field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetVelocityEstimate() VelocityEstimate {
	if o == nil || openapi.IsNil(o.VelocityEstimate) {
		var ret VelocityEstimate
		return ret
	}
	return *o.VelocityEstimate
}

// GetVelocityEstimateOk returns a tuple with the VelocityEstimate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetVelocityEstimateOk() (*VelocityEstimate, bool) {
	if o == nil || openapi.IsNil(o.VelocityEstimate) {
		return nil, false
	}
	return o.VelocityEstimate, true
}

// HasVelocityEstimate returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasVelocityEstimate() bool {
	if o != nil && !openapi.IsNil(o.VelocityEstimate) {
		return true
	}

	return false
}

// SetVelocityEstimate gets a reference to the given VelocityEstimate and assigns it to the VelocityEstimate field.
func (o *ProvidePosInfo) SetVelocityEstimate(v VelocityEstimate) {
	o.VelocityEstimate = &v
}

// GetPositioningDataList returns the PositioningDataList field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetPositioningDataList() []PositioningMethodAndUsage {
	if o == nil || openapi.IsNil(o.PositioningDataList) {
		var ret []PositioningMethodAndUsage
		return ret
	}
	return o.PositioningDataList
}

// GetPositioningDataListOk returns a tuple with the PositioningDataList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetPositioningDataListOk() ([]PositioningMethodAndUsage, bool) {
	if o == nil || openapi.IsNil(o.PositioningDataList) {
		return nil, false
	}
	return o.PositioningDataList, true
}

// HasPositioningDataList returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasPositioningDataList() bool {
	if o != nil && !openapi.IsNil(o.PositioningDataList) {
		return true
	}

	return false
}

// SetPositioningDataList gets a reference to the given []PositioningMethodAndUsage and assigns it to the PositioningDataList field.
func (o *ProvidePosInfo) SetPositioningDataList(v []PositioningMethodAndUsage) {
	o.PositioningDataList = v
}

// GetGnssPositioningDataList returns the GnssPositioningDataList field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetGnssPositioningDataList() []GnssPositioningMethodAndUsage {
	if o == nil || openapi.IsNil(o.GnssPositioningDataList) {
		var ret []GnssPositioningMethodAndUsage
		return ret
	}
	return o.GnssPositioningDataList
}

// GetGnssPositioningDataListOk returns a tuple with the GnssPositioningDataList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetGnssPositioningDataListOk() ([]GnssPositioningMethodAndUsage, bool) {
	if o == nil || openapi.IsNil(o.GnssPositioningDataList) {
		return nil, false
	}
	return o.GnssPositioningDataList, true
}

// HasGnssPositioningDataList returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasGnssPositioningDataList() bool {
	if o != nil && !openapi.IsNil(o.GnssPositioningDataList) {
		return true
	}

	return false
}

// SetGnssPositioningDataList gets a reference to the given []GnssPositioningMethodAndUsage and assigns it to the GnssPositioningDataList field.
func (o *ProvidePosInfo) SetGnssPositioningDataList(v []GnssPositioningMethodAndUsage) {
	o.GnssPositioningDataList = v
}

// GetEcgi returns the Ecgi field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetEcgi() Ecgi {
	if o == nil || openapi.IsNil(o.Ecgi) {
		var ret Ecgi
		return ret
	}
	return *o.Ecgi
}

// GetEcgiOk returns a tuple with the Ecgi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetEcgiOk() (*Ecgi, bool) {
	if o == nil || openapi.IsNil(o.Ecgi) {
		return nil, false
	}
	return o.Ecgi, true
}

// HasEcgi returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasEcgi() bool {
	if o != nil && !openapi.IsNil(o.Ecgi) {
		return true
	}

	return false
}

// SetEcgi gets a reference to the given Ecgi and assigns it to the Ecgi field.
func (o *ProvidePosInfo) SetEcgi(v Ecgi) {
	o.Ecgi = &v
}

// GetNcgi returns the Ncgi field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetNcgi() Ncgi {
	if o == nil || openapi.IsNil(o.Ncgi) {
		var ret Ncgi
		return ret
	}
	return *o.Ncgi
}

// GetNcgiOk returns a tuple with the Ncgi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetNcgiOk() (*Ncgi, bool) {
	if o == nil || openapi.IsNil(o.Ncgi) {
		return nil, false
	}
	return o.Ncgi, true
}

// HasNcgi returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasNcgi() bool {
	if o != nil && !openapi.IsNil(o.Ncgi) {
		return true
	}

	return false
}

// SetNcgi gets a reference to the given Ncgi and assigns it to the Ncgi field.
func (o *ProvidePosInfo) SetNcgi(v Ncgi) {
	o.Ncgi = &v
}

// GetTargetServingNode returns the TargetServingNode field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetTargetServingNode() string {
	if o == nil || openapi.IsNil(o.TargetServingNode) {
		var ret string
		return ret
	}
	return *o.TargetServingNode
}

// GetTargetServingNodeOk returns a tuple with the TargetServingNode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetTargetServingNodeOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.TargetServingNode) {
		return nil, false
	}
	return o.TargetServingNode, true
}

// HasTargetServingNode returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasTargetServingNode() bool {
	if o != nil && !openapi.IsNil(o.TargetServingNode) {
		return true
	}

	return false
}

// SetTargetServingNode gets a reference to the given string and assigns it to the TargetServingNode field.
func (o *ProvidePosInfo) SetTargetServingNode(v string) {
	o.TargetServingNode = &v
}

// GetTargetMmeName returns the TargetMmeName field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetTargetMmeName() string {
	if o == nil || openapi.IsNil(o.TargetMmeName) {
		var ret string
		return ret
	}
	return *o.TargetMmeName
}

// GetTargetMmeNameOk returns a tuple with the TargetMmeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetTargetMmeNameOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.TargetMmeName) {
		return nil, false
	}
	return o.TargetMmeName, true
}

// HasTargetMmeName returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasTargetMmeName() bool {
	if o != nil && !openapi.IsNil(o.TargetMmeName) {
		return true
	}

	return false
}

// SetTargetMmeName gets a reference to the given string and assigns it to the TargetMmeName field.
func (o *ProvidePosInfo) SetTargetMmeName(v string) {
	o.TargetMmeName = &v
}

// GetTargetMmeRealm returns the TargetMmeRealm field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetTargetMmeRealm() string {
	if o == nil || openapi.IsNil(o.TargetMmeRealm) {
		var ret string
		return ret
	}
	return *o.TargetMmeRealm
}

// GetTargetMmeRealmOk returns a tuple with the TargetMmeRealm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetTargetMmeRealmOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.TargetMmeRealm) {
		return nil, false
	}
	return o.TargetMmeRealm, true
}

// HasTargetMmeRealm returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasTargetMmeRealm() bool {
	if o != nil && !openapi.IsNil(o.TargetMmeRealm) {
		return true
	}

	return false
}

// SetTargetMmeRealm gets a reference to the given string and assigns it to the TargetMmeRealm field.
func (o *ProvidePosInfo) SetTargetMmeRealm(v string) {
	o.TargetMmeRealm = &v
}

// GetUtranSrvccInd returns the UtranSrvccInd field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetUtranSrvccInd() bool {
	if o == nil || openapi.IsNil(o.UtranSrvccInd) {
		var ret bool
		return ret
	}
	return *o.UtranSrvccInd
}

// GetUtranSrvccIndOk returns a tuple with the UtranSrvccInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetUtranSrvccIndOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.UtranSrvccInd) {
		return nil, false
	}
	return o.UtranSrvccInd, true
}

// HasUtranSrvccInd returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasUtranSrvccInd() bool {
	if o != nil && !openapi.IsNil(o.UtranSrvccInd) {
		return true
	}

	return false
}

// SetUtranSrvccInd gets a reference to the given bool and assigns it to the UtranSrvccInd field.
func (o *ProvidePosInfo) SetUtranSrvccInd(v bool) {
	o.UtranSrvccInd = &v
}

// GetCivicAddress returns the CivicAddress field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetCivicAddress() CivicAddress {
	if o == nil || openapi.IsNil(o.CivicAddress) {
		var ret CivicAddress
		return ret
	}
	return *o.CivicAddress
}

// GetCivicAddressOk returns a tuple with the CivicAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetCivicAddressOk() (*CivicAddress, bool) {
	if o == nil || openapi.IsNil(o.CivicAddress) {
		return nil, false
	}
	return o.CivicAddress, true
}

// HasCivicAddress returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasCivicAddress() bool {
	if o != nil && !openapi.IsNil(o.CivicAddress) {
		return true
	}

	return false
}

// SetCivicAddress gets a reference to the given CivicAddress and assigns it to the CivicAddress field.
func (o *ProvidePosInfo) SetCivicAddress(v CivicAddress) {
	o.CivicAddress = &v
}

// GetBarometricPressure returns the BarometricPressure field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetBarometricPressure() int32 {
	if o == nil || openapi.IsNil(o.BarometricPressure) {
		var ret int32
		return ret
	}
	return *o.BarometricPressure
}

// GetBarometricPressureOk returns a tuple with the BarometricPressure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetBarometricPressureOk() (*int32, bool) {
	if o == nil || openapi.IsNil(o.BarometricPressure) {
		return nil, false
	}
	return o.BarometricPressure, true
}

// HasBarometricPressure returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasBarometricPressure() bool {
	if o != nil && !openapi.IsNil(o.BarometricPressure) {
		return true
	}

	return false
}

// SetBarometricPressure gets a reference to the given int32 and assigns it to the BarometricPressure field.
func (o *ProvidePosInfo) SetBarometricPressure(v int32) {
	o.BarometricPressure = &v
}

// GetAltitude returns the Altitude field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetAltitude() float64 {
	if o == nil || openapi.IsNil(o.Altitude) {
		var ret float64
		return ret
	}
	return *o.Altitude
}

// GetAltitudeOk returns a tuple with the Altitude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetAltitudeOk() (*float64, bool) {
	if o == nil || openapi.IsNil(o.Altitude) {
		return nil, false
	}
	return o.Altitude, true
}

// HasAltitude returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasAltitude() bool {
	if o != nil && !openapi.IsNil(o.Altitude) {
		return true
	}

	return false
}

// SetAltitude gets a reference to the given float64 and assigns it to the Altitude field.
func (o *ProvidePosInfo) SetAltitude(v float64) {
	o.Altitude = &v
}

// GetSupportedFeatures returns the SupportedFeatures field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetSupportedFeatures() string {
	if o == nil || openapi.IsNil(o.SupportedFeatures) {
		var ret string
		return ret
	}
	return *o.SupportedFeatures
}

// GetSupportedFeaturesOk returns a tuple with the SupportedFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetSupportedFeaturesOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.SupportedFeatures) {
		return nil, false
	}
	return o.SupportedFeatures, true
}

// HasSupportedFeatures returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasSupportedFeatures() bool {
	if o != nil && !openapi.IsNil(o.SupportedFeatures) {
		return true
	}

	return false
}

// SetSupportedFeatures gets a reference to the given string and assigns it to the SupportedFeatures field.
func (o *ProvidePosInfo) SetSupportedFeatures(v string) {
	o.SupportedFeatures = &v
}

// GetServingLMFIdentification returns the ServingLMFIdentification field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetServingLMFIdentification() string {
	if o == nil || openapi.IsNil(o.ServingLMFIdentification) {
		var ret string
		return ret
	}
	return *o.ServingLMFIdentification
}

// GetServingLMFIdentificationOk returns a tuple with the ServingLMFIdentification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetServingLMFIdentificationOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.ServingLMFIdentification) {
		return nil, false
	}
	return o.ServingLMFIdentification, true
}

// HasServingLMFIdentification returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasServingLMFIdentification() bool {
	if o != nil && !openapi.IsNil(o.ServingLMFIdentification) {
		return true
	}

	return false
}

// SetServingLMFIdentification gets a reference to the given string and assigns it to the ServingLMFIdentification field.
func (o *ProvidePosInfo) SetServingLMFIdentification(v string) {
	o.ServingLMFIdentification = &v
}

// GetLocationPrivacyVerResult returns the LocationPrivacyVerResult field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetLocationPrivacyVerResult() LocationPrivacyVerResult {
	if o == nil || openapi.IsNil(o.LocationPrivacyVerResult) {
		var ret LocationPrivacyVerResult
		return ret
	}
	return *o.LocationPrivacyVerResult
}

// GetLocationPrivacyVerResultOk returns a tuple with the LocationPrivacyVerResult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetLocationPrivacyVerResultOk() (*LocationPrivacyVerResult, bool) {
	if o == nil || openapi.IsNil(o.LocationPrivacyVerResult) {
		return nil, false
	}
	return o.LocationPrivacyVerResult, true
}

// HasLocationPrivacyVerResult returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasLocationPrivacyVerResult() bool {
	if o != nil && !openapi.IsNil(o.LocationPrivacyVerResult) {
		return true
	}

	return false
}

// SetLocationPrivacyVerResult gets a reference to the given LocationPrivacyVerResult and assigns it to the LocationPrivacyVerResult field.
func (o *ProvidePosInfo) SetLocationPrivacyVerResult(v LocationPrivacyVerResult) {
	o.LocationPrivacyVerResult = &v
}

// GetAchievedQos returns the AchievedQos field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetAchievedQos() MinorLocationQoS {
	if o == nil || openapi.IsNil(o.AchievedQos) {
		var ret MinorLocationQoS
		return ret
	}
	return *o.AchievedQos
}

// GetAchievedQosOk returns a tuple with the AchievedQos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetAchievedQosOk() (*MinorLocationQoS, bool) {
	if o == nil || openapi.IsNil(o.AchievedQos) {
		return nil, false
	}
	return o.AchievedQos, true
}

// HasAchievedQos returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasAchievedQos() bool {
	if o != nil && !openapi.IsNil(o.AchievedQos) {
		return true
	}

	return false
}

// SetAchievedQos gets a reference to the given MinorLocationQoS and assigns it to the AchievedQos field.
func (o *ProvidePosInfo) SetAchievedQos(v MinorLocationQoS) {
	o.AchievedQos = &v
}

// GetDirectReportInd returns the DirectReportInd field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetDirectReportInd() bool {
	if o == nil || openapi.IsNil(o.DirectReportInd) {
		var ret bool
		return ret
	}
	return *o.DirectReportInd
}

// GetDirectReportIndOk returns a tuple with the DirectReportInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetDirectReportIndOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.DirectReportInd) {
		return nil, false
	}
	return o.DirectReportInd, true
}

// HasDirectReportInd returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasDirectReportInd() bool {
	if o != nil && !openapi.IsNil(o.DirectReportInd) {
		return true
	}

	return false
}

// SetDirectReportInd gets a reference to the given bool and assigns it to the DirectReportInd field.
func (o *ProvidePosInfo) SetDirectReportInd(v bool) {
	o.DirectReportInd = &v
}

// GetAcceptedPeriodicEventInfo returns the AcceptedPeriodicEventInfo field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetAcceptedPeriodicEventInfo() PeriodicEventInfo {
	if o == nil || openapi.IsNil(o.AcceptedPeriodicEventInfo) {
		var ret PeriodicEventInfo
		return ret
	}
	return *o.AcceptedPeriodicEventInfo
}

// GetAcceptedPeriodicEventInfoOk returns a tuple with the AcceptedPeriodicEventInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetAcceptedPeriodicEventInfoOk() (*PeriodicEventInfo, bool) {
	if o == nil || openapi.IsNil(o.AcceptedPeriodicEventInfo) {
		return nil, false
	}
	return o.AcceptedPeriodicEventInfo, true
}

// HasAcceptedPeriodicEventInfo returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasAcceptedPeriodicEventInfo() bool {
	if o != nil && !openapi.IsNil(o.AcceptedPeriodicEventInfo) {
		return true
	}

	return false
}

// SetAcceptedPeriodicEventInfo gets a reference to the given PeriodicEventInfo and assigns it to the AcceptedPeriodicEventInfo field.
func (o *ProvidePosInfo) SetAcceptedPeriodicEventInfo(v PeriodicEventInfo) {
	o.AcceptedPeriodicEventInfo = &v
}

// GetHaGnssMetrics returns the HaGnssMetrics field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetHaGnssMetrics() HighAccuracyGnssMetrics {
	if o == nil || openapi.IsNil(o.HaGnssMetrics) {
		var ret HighAccuracyGnssMetrics
		return ret
	}
	return *o.HaGnssMetrics
}

// GetHaGnssMetricsOk returns a tuple with the HaGnssMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetHaGnssMetricsOk() (*HighAccuracyGnssMetrics, bool) {
	if o == nil || openapi.IsNil(o.HaGnssMetrics) {
		return nil, false
	}
	return o.HaGnssMetrics, true
}

// HasHaGnssMetrics returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasHaGnssMetrics() bool {
	if o != nil && !openapi.IsNil(o.HaGnssMetrics) {
		return true
	}

	return false
}

// SetHaGnssMetrics gets a reference to the given HighAccuracyGnssMetrics and assigns it to the HaGnssMetrics field.
func (o *ProvidePosInfo) SetHaGnssMetrics(v HighAccuracyGnssMetrics) {
	o.HaGnssMetrics = &v
}

// GetIndoorOutdoorInd returns the IndoorOutdoorInd field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetIndoorOutdoorInd() IndoorOutdoorInd {
	if o == nil || openapi.IsNil(o.IndoorOutdoorInd) {
		var ret IndoorOutdoorInd
		return ret
	}
	return *o.IndoorOutdoorInd
}

// GetIndoorOutdoorIndOk returns a tuple with the IndoorOutdoorInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetIndoorOutdoorIndOk() (*IndoorOutdoorInd, bool) {
	if o == nil || openapi.IsNil(o.IndoorOutdoorInd) {
		return nil, false
	}
	return o.IndoorOutdoorInd, true
}

// HasIndoorOutdoorInd returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasIndoorOutdoorInd() bool {
	if o != nil && !openapi.IsNil(o.IndoorOutdoorInd) {
		return true
	}

	return false
}

// SetIndoorOutdoorInd gets a reference to the given IndoorOutdoorInd and assigns it to the IndoorOutdoorInd field.
func (o *ProvidePosInfo) SetIndoorOutdoorInd(v IndoorOutdoorInd) {
	o.IndoorOutdoorInd = &v
}

// GetLosNlosMeasureInd returns the LosNlosMeasureInd field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetLosNlosMeasureInd() LosNlosMeasureInd {
	if o == nil || openapi.IsNil(o.LosNlosMeasureInd) {
		var ret LosNlosMeasureInd
		return ret
	}
	return *o.LosNlosMeasureInd
}

// GetLosNlosMeasureIndOk returns a tuple with the LosNlosMeasureInd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetLosNlosMeasureIndOk() (*LosNlosMeasureInd, bool) {
	if o == nil || openapi.IsNil(o.LosNlosMeasureInd) {
		return nil, false
	}
	return o.LosNlosMeasureInd, true
}

// HasLosNlosMeasureInd returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasLosNlosMeasureInd() bool {
	if o != nil && !openapi.IsNil(o.LosNlosMeasureInd) {
		return true
	}

	return false
}

// SetLosNlosMeasureInd gets a reference to the given LosNlosMeasureInd and assigns it to the LosNlosMeasureInd field.
func (o *ProvidePosInfo) SetLosNlosMeasureInd(v LosNlosMeasureInd) {
	o.LosNlosMeasureInd = &v
}

// GetRelatedApplicationlayerId returns the RelatedApplicationlayerId field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetRelatedApplicationlayerId() string {
	if o == nil || openapi.IsNil(o.RelatedApplicationlayerId) {
		var ret string
		return ret
	}
	return *o.RelatedApplicationlayerId
}

// GetRelatedApplicationlayerIdOk returns a tuple with the RelatedApplicationlayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetRelatedApplicationlayerIdOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.RelatedApplicationlayerId) {
		return nil, false
	}
	return o.RelatedApplicationlayerId, true
}

// HasRelatedApplicationlayerId returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasRelatedApplicationlayerId() bool {
	if o != nil && !openapi.IsNil(o.RelatedApplicationlayerId) {
		return true
	}

	return false
}

// SetRelatedApplicationlayerId gets a reference to the given string and assigns it to the RelatedApplicationlayerId field.
func (o *ProvidePosInfo) SetRelatedApplicationlayerId(v string) {
	o.RelatedApplicationlayerId = &v
}

// GetDistanceDirection returns the DistanceDirection field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetDistanceDirection() RangeDirection {
	if o == nil || openapi.IsNil(o.DistanceDirection) {
		var ret RangeDirection
		return ret
	}
	return *o.DistanceDirection
}

// GetDistanceDirectionOk returns a tuple with the DistanceDirection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetDistanceDirectionOk() (*RangeDirection, bool) {
	if o == nil || openapi.IsNil(o.DistanceDirection) {
		return nil, false
	}
	return o.DistanceDirection, true
}

// HasDistanceDirection returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasDistanceDirection() bool {
	if o != nil && !openapi.IsNil(o.DistanceDirection) {
		return true
	}

	return false
}

// SetDistanceDirection gets a reference to the given RangeDirection and assigns it to the DistanceDirection field.
func (o *ProvidePosInfo) SetDistanceDirection(v RangeDirection) {
	o.DistanceDirection = &v
}

// GetVar2dRelativeLocation returns the Var2dRelativeLocation field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetVar2dRelativeLocation() TwoDRelativeLocation {
	if o == nil || openapi.IsNil(o.Var2dRelativeLocation) {
		var ret TwoDRelativeLocation
		return ret
	}
	return *o.Var2dRelativeLocation
}

// GetVar2dRelativeLocationOk returns a tuple with the Var2dRelativeLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetVar2dRelativeLocationOk() (*TwoDRelativeLocation, bool) {
	if o == nil || openapi.IsNil(o.Var2dRelativeLocation) {
		return nil, false
	}
	return o.Var2dRelativeLocation, true
}

// HasVar2dRelativeLocation returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasVar2dRelativeLocation() bool {
	if o != nil && !openapi.IsNil(o.Var2dRelativeLocation) {
		return true
	}

	return false
}

// SetVar2dRelativeLocation gets a reference to the given TwoDRelativeLocation and assigns it to the Var2dRelativeLocation field.
func (o *ProvidePosInfo) SetVar2dRelativeLocation(v TwoDRelativeLocation) {
	o.Var2dRelativeLocation = &v
}

// GetVar3dRelativeLocation returns the Var3dRelativeLocation field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetVar3dRelativeLocation() ThreeDRelativeLocation {
	if o == nil || openapi.IsNil(o.Var3dRelativeLocation) {
		var ret ThreeDRelativeLocation
		return ret
	}
	return *o.Var3dRelativeLocation
}

// GetVar3dRelativeLocationOk returns a tuple with the Var3dRelativeLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetVar3dRelativeLocationOk() (*ThreeDRelativeLocation, bool) {
	if o == nil || openapi.IsNil(o.Var3dRelativeLocation) {
		return nil, false
	}
	return o.Var3dRelativeLocation, true
}

// HasVar3dRelativeLocation returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasVar3dRelativeLocation() bool {
	if o != nil && !openapi.IsNil(o.Var3dRelativeLocation) {
		return true
	}

	return false
}

// SetVar3dRelativeLocation gets a reference to the given ThreeDRelativeLocation and assigns it to the Var3dRelativeLocation field.
func (o *ProvidePosInfo) SetVar3dRelativeLocation(v ThreeDRelativeLocation) {
	o.Var3dRelativeLocation = &v
}

// GetRelativeVelocity returns the RelativeVelocity field value if set, zero value otherwise.
func (o *ProvidePosInfo) GetRelativeVelocity() VelocityEstimate {
	if o == nil || openapi.IsNil(o.RelativeVelocity) {
		var ret VelocityEstimate
		return ret
	}
	return *o.RelativeVelocity
}

// GetRelativeVelocityOk returns a tuple with the RelativeVelocity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProvidePosInfo) GetRelativeVelocityOk() (*VelocityEstimate, bool) {
	if o == nil || openapi.IsNil(o.RelativeVelocity) {
		return nil, false
	}
	return o.RelativeVelocity, true
}

// HasRelativeVelocity returns a boolean if a field has been set.
func (o *ProvidePosInfo) HasRelativeVelocity() bool {
	if o != nil && !openapi.IsNil(o.RelativeVelocity) {
		return true
	}

	return false
}

// SetRelativeVelocity gets a reference to the given VelocityEstimate and assigns it to the RelativeVelocity field.
func (o *ProvidePosInfo) SetRelativeVelocity(v VelocityEstimate) {
	o.RelativeVelocity = &v
}

func (o ProvidePosInfo) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.LocationEstimate) {
		toSerialize["locationEstimate"] = o.LocationEstimate
	}
	if !openapi.IsNil(o.AccuracyFulfilmentIndicator) {
		toSerialize["accuracyFulfilmentIndicator"] = o.AccuracyFulfilmentIndicator
	}
	if !openapi.IsNil(o.AgeOfLocationEstimate) {
		toSerialize["ageOfLocationEstimate"] = o.AgeOfLocationEstimate
	}
	if !openapi.IsNil(o.TimestampOfLocationEstimate) {
		toSerialize["timestampOfLocationEstimate"] = o.TimestampOfLocationEstimate
	}
	if !openapi.IsNil(o.VelocityEstimate) {
		toSerialize["velocityEstimate"] = o.VelocityEstimate
	}
	if !openapi.IsNil(o.PositioningDataList) {
		toSerialize["positioningDataList"] = o.PositioningDataList
	}
	if !openapi.IsNil(o.GnssPositioningDataList) {
		toSerialize["gnssPositioningDataList"] = o.GnssPositioningDataList
	}
	if !openapi.IsNil(o.Ecgi) {
		toSerialize["ecgi"] = o.Ecgi
	}
	if !openapi.IsNil(o.Ncgi) {
		toSerialize["ncgi"] = o.Ncgi
	}
	if !openapi.IsNil(o.TargetServingNode) {
		toSerialize["targetServingNode"] = o.TargetServingNode
	}
	if !openapi.IsNil(o.TargetMmeName) {
		toSerialize["targetMmeName"] = o.TargetMmeName
	}
	if !openapi.IsNil(o.TargetMmeRealm) {
		toSerialize["targetMmeRealm"] = o.TargetMmeRealm
	}
	if !openapi.IsNil(o.UtranSrvccInd) {
		toSerialize["utranSrvccInd"] = o.UtranSrvccInd
	}
	if !openapi.IsNil(o.CivicAddress) {
		toSerialize["civicAddress"] = o.CivicAddress
	}
	if !openapi.IsNil(o.BarometricPressure) {
		toSerialize["barometricPressure"] = o.BarometricPressure
	}
	if !openapi.IsNil(o.Altitude) {
		toSerialize["altitude"] = o.Altitude
	}
	if !openapi.IsNil(o.SupportedFeatures) {
		toSerialize["supportedFeatures"] = o.SupportedFeatures
	}
	if !openapi.IsNil(o.ServingLMFIdentification) {
		toSerialize["servingLMFIdentification"] = o.ServingLMFIdentification
	}
	if !openapi.IsNil(o.LocationPrivacyVerResult) {
		toSerialize["locationPrivacyVerResult"] = o.LocationPrivacyVerResult
	}
	if !openapi.IsNil(o.AchievedQos) {
		toSerialize["achievedQos"] = o.AchievedQos
	}
	if !openapi.IsNil(o.DirectReportInd) {
		toSerialize["directReportInd"] = o.DirectReportInd
	}
	if !openapi.IsNil(o.AcceptedPeriodicEventInfo) {
		toSerialize["acceptedPeriodicEventInfo"] = o.AcceptedPeriodicEventInfo
	}
	if !openapi.IsNil(o.HaGnssMetrics) {
		toSerialize["haGnssMetrics"] = o.HaGnssMetrics
	}
	if !openapi.IsNil(o.IndoorOutdoorInd) {
		toSerialize["indoorOutdoorInd"] = o.IndoorOutdoorInd
	}
	if !openapi.IsNil(o.LosNlosMeasureInd) {
		toSerialize["losNlosMeasureInd"] = o.LosNlosMeasureInd
	}
	if !openapi.IsNil(o.RelatedApplicationlayerId) {
		toSerialize["relatedApplicationlayerId"] = o.RelatedApplicationlayerId
	}
	if !openapi.IsNil(o.DistanceDirection) {
		toSerialize["distanceDirection"] = o.DistanceDirection
	}
	if !openapi.IsNil(o.Var2dRelativeLocation) {
		toSerialize["2dRelativeLocation"] = o.Var2dRelativeLocation
	}
	if !openapi.IsNil(o.Var3dRelativeLocation) {
		toSerialize["3dRelativeLocation"] = o.Var3dRelativeLocation
	}
	if !openapi.IsNil(o.RelativeVelocity) {
		toSerialize["relativeVelocity"] = o.RelativeVelocity
	}
	return toSerialize, nil
}

type NullableProvidePosInfo struct {
	value *ProvidePosInfo
	isSet bool
}

func (v NullableProvidePosInfo) Get() *ProvidePosInfo {
	return v.value
}

func (v *NullableProvidePosInfo) Set(val *ProvidePosInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableProvidePosInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableProvidePosInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProvidePosInfo(val *ProvidePosInfo) *NullableProvidePosInfo {
	return &NullableProvidePosInfo{value: val, isSet: true}
}

func (v NullableProvidePosInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProvidePosInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
