// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the E2eDataVolTransTimePerUe type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &E2eDataVolTransTimePerUe{}

// E2eDataVolTransTimePerUe Represents the E2E data volume transfer time per UE.
type E2eDataVolTransTimePerUe struct {
	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501.
	Supi *string
	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.
	Gpsi   *string
	Snssai *Snssai
	// String providing an application identifier.
	AppId *string
	UeLoc *UserLocation
	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\").
	Dnn              *string
	SpatialValidity  *NetworkAreaInfo
	ValidityPeriod   *TimeWindow
	DataVolTransTime *DataVolumeTransferTime
}

// NewE2eDataVolTransTimePerUe instantiates a new E2eDataVolTransTimePerUe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewE2eDataVolTransTimePerUe() *E2eDataVolTransTimePerUe {
	this := E2eDataVolTransTimePerUe{}
	return &this
}

// NewE2eDataVolTransTimePerUeWithDefaults instantiates a new E2eDataVolTransTimePerUe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewE2eDataVolTransTimePerUeWithDefaults() *E2eDataVolTransTimePerUe {
	this := E2eDataVolTransTimePerUe{}
	return &this
}

// GetSupi returns the Supi field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetSupi() string {
	if o == nil || openapi.IsNil(o.Supi) {
		var ret string
		return ret
	}
	return *o.Supi
}

// GetSupiOk returns a tuple with the Supi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetSupiOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.Supi) {
		return nil, false
	}
	return o.Supi, true
}

// HasSupi returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasSupi() bool {
	if o != nil && !openapi.IsNil(o.Supi) {
		return true
	}

	return false
}

// SetSupi gets a reference to the given string and assigns it to the Supi field.
func (o *E2eDataVolTransTimePerUe) SetSupi(v string) {
	o.Supi = &v
}

// GetGpsi returns the Gpsi field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetGpsi() string {
	if o == nil || openapi.IsNil(o.Gpsi) {
		var ret string
		return ret
	}
	return *o.Gpsi
}

// GetGpsiOk returns a tuple with the Gpsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetGpsiOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.Gpsi) {
		return nil, false
	}
	return o.Gpsi, true
}

// HasGpsi returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasGpsi() bool {
	if o != nil && !openapi.IsNil(o.Gpsi) {
		return true
	}

	return false
}

// SetGpsi gets a reference to the given string and assigns it to the Gpsi field.
func (o *E2eDataVolTransTimePerUe) SetGpsi(v string) {
	o.Gpsi = &v
}

// GetSnssai returns the Snssai field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetSnssai() Snssai {
	if o == nil || openapi.IsNil(o.Snssai) {
		var ret Snssai
		return ret
	}
	return *o.Snssai
}

// GetSnssaiOk returns a tuple with the Snssai field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetSnssaiOk() (*Snssai, bool) {
	if o == nil || openapi.IsNil(o.Snssai) {
		return nil, false
	}
	return o.Snssai, true
}

// HasSnssai returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasSnssai() bool {
	if o != nil && !openapi.IsNil(o.Snssai) {
		return true
	}

	return false
}

// SetSnssai gets a reference to the given Snssai and assigns it to the Snssai field.
func (o *E2eDataVolTransTimePerUe) SetSnssai(v Snssai) {
	o.Snssai = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetAppId() string {
	if o == nil || openapi.IsNil(o.AppId) {
		var ret string
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetAppIdOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasAppId() bool {
	if o != nil && !openapi.IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given string and assigns it to the AppId field.
func (o *E2eDataVolTransTimePerUe) SetAppId(v string) {
	o.AppId = &v
}

// GetUeLoc returns the UeLoc field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetUeLoc() UserLocation {
	if o == nil || openapi.IsNil(o.UeLoc) {
		var ret UserLocation
		return ret
	}
	return *o.UeLoc
}

// GetUeLocOk returns a tuple with the UeLoc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetUeLocOk() (*UserLocation, bool) {
	if o == nil || openapi.IsNil(o.UeLoc) {
		return nil, false
	}
	return o.UeLoc, true
}

// HasUeLoc returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasUeLoc() bool {
	if o != nil && !openapi.IsNil(o.UeLoc) {
		return true
	}

	return false
}

// SetUeLoc gets a reference to the given UserLocation and assigns it to the UeLoc field.
func (o *E2eDataVolTransTimePerUe) SetUeLoc(v UserLocation) {
	o.UeLoc = &v
}

// GetDnn returns the Dnn field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetDnn() string {
	if o == nil || openapi.IsNil(o.Dnn) {
		var ret string
		return ret
	}
	return *o.Dnn
}

// GetDnnOk returns a tuple with the Dnn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetDnnOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.Dnn) {
		return nil, false
	}
	return o.Dnn, true
}

// HasDnn returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasDnn() bool {
	if o != nil && !openapi.IsNil(o.Dnn) {
		return true
	}

	return false
}

// SetDnn gets a reference to the given string and assigns it to the Dnn field.
func (o *E2eDataVolTransTimePerUe) SetDnn(v string) {
	o.Dnn = &v
}

// GetSpatialValidity returns the SpatialValidity field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetSpatialValidity() NetworkAreaInfo {
	if o == nil || openapi.IsNil(o.SpatialValidity) {
		var ret NetworkAreaInfo
		return ret
	}
	return *o.SpatialValidity
}

// GetSpatialValidityOk returns a tuple with the SpatialValidity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetSpatialValidityOk() (*NetworkAreaInfo, bool) {
	if o == nil || openapi.IsNil(o.SpatialValidity) {
		return nil, false
	}
	return o.SpatialValidity, true
}

// HasSpatialValidity returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasSpatialValidity() bool {
	if o != nil && !openapi.IsNil(o.SpatialValidity) {
		return true
	}

	return false
}

// SetSpatialValidity gets a reference to the given NetworkAreaInfo and assigns it to the SpatialValidity field.
func (o *E2eDataVolTransTimePerUe) SetSpatialValidity(v NetworkAreaInfo) {
	o.SpatialValidity = &v
}

// GetValidityPeriod returns the ValidityPeriod field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetValidityPeriod() TimeWindow {
	if o == nil || openapi.IsNil(o.ValidityPeriod) {
		var ret TimeWindow
		return ret
	}
	return *o.ValidityPeriod
}

// GetValidityPeriodOk returns a tuple with the ValidityPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetValidityPeriodOk() (*TimeWindow, bool) {
	if o == nil || openapi.IsNil(o.ValidityPeriod) {
		return nil, false
	}
	return o.ValidityPeriod, true
}

// HasValidityPeriod returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasValidityPeriod() bool {
	if o != nil && !openapi.IsNil(o.ValidityPeriod) {
		return true
	}

	return false
}

// SetValidityPeriod gets a reference to the given TimeWindow and assigns it to the ValidityPeriod field.
func (o *E2eDataVolTransTimePerUe) SetValidityPeriod(v TimeWindow) {
	o.ValidityPeriod = &v
}

// GetDataVolTransTime returns the DataVolTransTime field value if set, zero value otherwise.
func (o *E2eDataVolTransTimePerUe) GetDataVolTransTime() DataVolumeTransferTime {
	if o == nil || openapi.IsNil(o.DataVolTransTime) {
		var ret DataVolumeTransferTime
		return ret
	}
	return *o.DataVolTransTime
}

// GetDataVolTransTimeOk returns a tuple with the DataVolTransTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *E2eDataVolTransTimePerUe) GetDataVolTransTimeOk() (*DataVolumeTransferTime, bool) {
	if o == nil || openapi.IsNil(o.DataVolTransTime) {
		return nil, false
	}
	return o.DataVolTransTime, true
}

// HasDataVolTransTime returns a boolean if a field has been set.
func (o *E2eDataVolTransTimePerUe) HasDataVolTransTime() bool {
	if o != nil && !openapi.IsNil(o.DataVolTransTime) {
		return true
	}

	return false
}

// SetDataVolTransTime gets a reference to the given DataVolumeTransferTime and assigns it to the DataVolTransTime field.
func (o *E2eDataVolTransTimePerUe) SetDataVolTransTime(v DataVolumeTransferTime) {
	o.DataVolTransTime = &v
}

func (o E2eDataVolTransTimePerUe) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.Supi) {
		toSerialize["supi"] = o.Supi
	}
	if !openapi.IsNil(o.Gpsi) {
		toSerialize["gpsi"] = o.Gpsi
	}
	if !openapi.IsNil(o.Snssai) {
		toSerialize["snssai"] = o.Snssai
	}
	if !openapi.IsNil(o.AppId) {
		toSerialize["appId"] = o.AppId
	}
	if !openapi.IsNil(o.UeLoc) {
		toSerialize["ueLoc"] = o.UeLoc
	}
	if !openapi.IsNil(o.Dnn) {
		toSerialize["dnn"] = o.Dnn
	}
	if !openapi.IsNil(o.SpatialValidity) {
		toSerialize["spatialValidity"] = o.SpatialValidity
	}
	if !openapi.IsNil(o.ValidityPeriod) {
		toSerialize["validityPeriod"] = o.ValidityPeriod
	}
	if !openapi.IsNil(o.DataVolTransTime) {
		toSerialize["dataVolTransTime"] = o.DataVolTransTime
	}
	return toSerialize, nil
}

type NullableE2eDataVolTransTimePerUe struct {
	value *E2eDataVolTransTimePerUe
	isSet bool
}

func (v NullableE2eDataVolTransTimePerUe) Get() *E2eDataVolTransTimePerUe {
	return v.value
}

func (v *NullableE2eDataVolTransTimePerUe) Set(val *E2eDataVolTransTimePerUe) {
	v.value = val
	v.isSet = true
}

func (v NullableE2eDataVolTransTimePerUe) IsSet() bool {
	return v.isSet
}

func (v *NullableE2eDataVolTransTimePerUe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableE2eDataVolTransTimePerUe(val *E2eDataVolTransTimePerUe) *NullableE2eDataVolTransTimePerUe {
	return &NullableE2eDataVolTransTimePerUe{value: val, isSet: true}
}

func (v NullableE2eDataVolTransTimePerUe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableE2eDataVolTransTimePerUe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
