// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// PartitioningCriteria Possible values are: - \"TAC\": Type Allocation Code - \"SUBPLMN\": Subscriber PLMN ID - \"GEOAREA\": Geographical area, i.e. list(s) of TAI(s) - \"SNSSAI\": S-NSSAI - \"DNN\": DNN
type PartitioningCriteria string

// List of PartitioningCriteria
const (
	PARTITIONINGCRITERIA_TAC     PartitioningCriteria = "TAC"
	PARTITIONINGCRITERIA_SUBPLMN PartitioningCriteria = "SUBPLMN"
	PARTITIONINGCRITERIA_GEOAREA PartitioningCriteria = "GEOAREA"
	PARTITIONINGCRITERIA_SNSSAI  PartitioningCriteria = "SNSSAI"
	PARTITIONINGCRITERIA_DNN     PartitioningCriteria = "DNN"
)

// All allowed values of PartitioningCriteria enum
var AllowedPartitioningCriteriaEnumValues = []PartitioningCriteria{
	"TAC",
	"SUBPLMN",
	"GEOAREA",
	"SNSSAI",
	"DNN",
}

func (v *PartitioningCriteria) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PartitioningCriteria(value)
	if slices.Contains(AllowedPartitioningCriteriaEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid PartitioningCriteria", value)
}

// NewPartitioningCriteriaFromValue returns a pointer to a valid PartitioningCriteria
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPartitioningCriteriaFromValue(v string) (*PartitioningCriteria, error) {
	ev := PartitioningCriteria(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for PartitioningCriteria: valid values are %v", v, AllowedPartitioningCriteriaEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PartitioningCriteria) IsValid() bool {
	return slices.Contains(AllowedPartitioningCriteriaEnumValues, v)
}

// Ptr returns reference to PartitioningCriteria value
func (v PartitioningCriteria) Ptr() *PartitioningCriteria {
	return &v
}

type NullablePartitioningCriteria struct {
	value *PartitioningCriteria
	isSet bool
}

func (v NullablePartitioningCriteria) Get() *PartitioningCriteria {
	return v.value
}

func (v *NullablePartitioningCriteria) Set(val *PartitioningCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullablePartitioningCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullablePartitioningCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartitioningCriteria(val *PartitioningCriteria) *NullablePartitioningCriteria {
	return &NullablePartitioningCriteria{value: val, isSet: true}
}

func (v NullablePartitioningCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartitioningCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
