// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// N2InfoNotifyReason N2 Information Notify Reason
type N2InfoNotifyReason string

// List of N2InfoNotifyReason
const (
	N2INFONOTIFYREASON_HANDOVER_COMPLETED N2InfoNotifyReason = "HANDOVER_COMPLETED"
)

// All allowed values of N2InfoNotifyReason enum
var AllowedN2InfoNotifyReasonEnumValues = []N2InfoNotifyReason{
	"HANDOVER_COMPLETED",
}

func (v *N2InfoNotifyReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := N2InfoNotifyReason(value)
	if slices.Contains(AllowedN2InfoNotifyReasonEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid N2InfoNotifyReason", value)
}

// NewN2InfoNotifyReasonFromValue returns a pointer to a valid N2InfoNotifyReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewN2InfoNotifyReasonFromValue(v string) (*N2InfoNotifyReason, error) {
	ev := N2InfoNotifyReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for N2InfoNotifyReason: valid values are %v", v, AllowedN2InfoNotifyReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v N2InfoNotifyReason) IsValid() bool {
	return slices.Contains(AllowedN2InfoNotifyReasonEnumValues, v)
}

// Ptr returns reference to N2InfoNotifyReason value
func (v N2InfoNotifyReason) Ptr() *N2InfoNotifyReason {
	return &v
}

type NullableN2InfoNotifyReason struct {
	value *N2InfoNotifyReason
	isSet bool
}

func (v NullableN2InfoNotifyReason) Get() *N2InfoNotifyReason {
	return v.value
}

func (v *NullableN2InfoNotifyReason) Set(val *N2InfoNotifyReason) {
	v.value = val
	v.isSet = true
}

func (v NullableN2InfoNotifyReason) IsSet() bool {
	return v.isSet
}

func (v *NullableN2InfoNotifyReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableN2InfoNotifyReason(val *N2InfoNotifyReason) *NullableN2InfoNotifyReason {
	return &NullableN2InfoNotifyReason{value: val, isSet: true}
}

func (v NullableN2InfoNotifyReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableN2InfoNotifyReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
