// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the UeContextInAmfData type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &UeContextInAmfData{}

// UeContextInAmfData struct for UeContextInAmfData
type UeContextInAmfData struct {
	EpsInterworkingInfo *EpsInterworkingInfo `json:"epsInterworkingInfo,omitempty" yaml:"epsInterworkingInfo,omitempty"`
	// AMF information
	AmfInfo []AmfInfoUdm `json:"amfInfo,omitempty" yaml:"amfInfo,omitempty"`
}

// NewUeContextInAmfData instantiates a new UeContextInAmfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUeContextInAmfData() *UeContextInAmfData {
	this := UeContextInAmfData{}
	return &this
}

// NewUeContextInAmfDataWithDefaults instantiates a new UeContextInAmfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUeContextInAmfDataWithDefaults() *UeContextInAmfData {
	this := UeContextInAmfData{}
	return &this
}

// GetEpsInterworkingInfo returns the EpsInterworkingInfo field value if set, zero value otherwise.
func (o *UeContextInAmfData) GetEpsInterworkingInfo() EpsInterworkingInfo {
	if o == nil || openapi.IsNil(o.EpsInterworkingInfo) {
		var ret EpsInterworkingInfo
		return ret
	}
	return *o.EpsInterworkingInfo
}

// GetEpsInterworkingInfoOk returns a tuple with the EpsInterworkingInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeContextInAmfData) GetEpsInterworkingInfoOk() (*EpsInterworkingInfo, bool) {
	if o == nil || openapi.IsNil(o.EpsInterworkingInfo) {
		return nil, false
	}
	return o.EpsInterworkingInfo, true
}

// HasEpsInterworkingInfo returns a boolean if a field has been set.
func (o *UeContextInAmfData) HasEpsInterworkingInfo() bool {
	if o != nil && !openapi.IsNil(o.EpsInterworkingInfo) {
		return true
	}

	return false
}

// SetEpsInterworkingInfo gets a reference to the given EpsInterworkingInfo and assigns it to the EpsInterworkingInfo field.
func (o *UeContextInAmfData) SetEpsInterworkingInfo(v EpsInterworkingInfo) {
	o.EpsInterworkingInfo = &v
}

// GetAmfInfo returns the AmfInfo field value if set, zero value otherwise.
func (o *UeContextInAmfData) GetAmfInfo() []AmfInfoUdm {
	if o == nil || openapi.IsNil(o.AmfInfo) {
		var ret []AmfInfoUdm
		return ret
	}
	return o.AmfInfo
}

// GetAmfInfoOk returns a tuple with the AmfInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeContextInAmfData) GetAmfInfoOk() ([]AmfInfoUdm, bool) {
	if o == nil || openapi.IsNil(o.AmfInfo) {
		return nil, false
	}
	return o.AmfInfo, true
}

// HasAmfInfo returns a boolean if a field has been set.
func (o *UeContextInAmfData) HasAmfInfo() bool {
	if o != nil && !openapi.IsNil(o.AmfInfo) {
		return true
	}

	return false
}

// SetAmfInfo gets a reference to the given []AmfInfoUdm and assigns it to the AmfInfo field.
func (o *UeContextInAmfData) SetAmfInfo(v []AmfInfoUdm) {
	o.AmfInfo = v
}

func (o UeContextInAmfData) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.EpsInterworkingInfo) {
		toSerialize["epsInterworkingInfo"] = o.EpsInterworkingInfo
	}
	if !openapi.IsNil(o.AmfInfo) {
		toSerialize["amfInfo"] = o.AmfInfo
	}
	return toSerialize, nil
}

type NullableUeContextInAmfData struct {
	value *UeContextInAmfData
	isSet bool
}

func (v NullableUeContextInAmfData) Get() *UeContextInAmfData {
	return v.value
}

func (v *NullableUeContextInAmfData) Set(val *UeContextInAmfData) {
	v.value = val
	v.isSet = true
}

func (v NullableUeContextInAmfData) IsSet() bool {
	return v.isSet
}

func (v *NullableUeContextInAmfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUeContextInAmfData(val *UeContextInAmfData) *NullableUeContextInAmfData {
	return &NullableUeContextInAmfData{value: val, isSet: true}
}

func (v NullableUeContextInAmfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUeContextInAmfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
