// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nnwdaf_AnalyticsInfo

Nnwdaf_AnalyticsInfo Service API.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the ExceptionInfo type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &ExceptionInfo{}

// ExceptionInfo Represents the exceptions information provided by the AF.
type ExceptionInfo struct {
	IpTrafficFilter  *FlowInfo
	EthTrafficFilter *EthFlowDescription
	Exceps           []Exception
}

// NewExceptionInfo instantiates a new ExceptionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExceptionInfo(exceps []Exception) *ExceptionInfo {
	this := ExceptionInfo{}
	return &this
}

// NewExceptionInfoWithDefaults instantiates a new ExceptionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExceptionInfoWithDefaults() *ExceptionInfo {
	this := ExceptionInfo{}
	return &this
}

// GetIpTrafficFilter returns the IpTrafficFilter field value if set, zero value otherwise.
func (o *ExceptionInfo) GetIpTrafficFilter() FlowInfo {
	if o == nil || openapi.IsNil(o.IpTrafficFilter) {
		var ret FlowInfo
		return ret
	}
	return *o.IpTrafficFilter
}

// GetIpTrafficFilterOk returns a tuple with the IpTrafficFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExceptionInfo) GetIpTrafficFilterOk() (*FlowInfo, bool) {
	if o == nil || openapi.IsNil(o.IpTrafficFilter) {
		return nil, false
	}
	return o.IpTrafficFilter, true
}

// HasIpTrafficFilter returns a boolean if a field has been set.
func (o *ExceptionInfo) HasIpTrafficFilter() bool {
	if o != nil && !openapi.IsNil(o.IpTrafficFilter) {
		return true
	}

	return false
}

// SetIpTrafficFilter gets a reference to the given FlowInfo and assigns it to the IpTrafficFilter field.
func (o *ExceptionInfo) SetIpTrafficFilter(v FlowInfo) {
	o.IpTrafficFilter = &v
}

// GetEthTrafficFilter returns the EthTrafficFilter field value if set, zero value otherwise.
func (o *ExceptionInfo) GetEthTrafficFilter() EthFlowDescription {
	if o == nil || openapi.IsNil(o.EthTrafficFilter) {
		var ret EthFlowDescription
		return ret
	}
	return *o.EthTrafficFilter
}

// GetEthTrafficFilterOk returns a tuple with the EthTrafficFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExceptionInfo) GetEthTrafficFilterOk() (*EthFlowDescription, bool) {
	if o == nil || openapi.IsNil(o.EthTrafficFilter) {
		return nil, false
	}
	return o.EthTrafficFilter, true
}

// HasEthTrafficFilter returns a boolean if a field has been set.
func (o *ExceptionInfo) HasEthTrafficFilter() bool {
	if o != nil && !openapi.IsNil(o.EthTrafficFilter) {
		return true
	}

	return false
}

// SetEthTrafficFilter gets a reference to the given EthFlowDescription and assigns it to the EthTrafficFilter field.
func (o *ExceptionInfo) SetEthTrafficFilter(v EthFlowDescription) {
	o.EthTrafficFilter = &v
}

// GetExceps returns the Exceps field value
func (o *ExceptionInfo) GetExceps() []Exception {
	if o == nil {
		var ret []Exception
		return ret
	}

	return o.Exceps
}

// GetExcepsOk returns a tuple with the Exceps field value
// and a boolean to check if the value has been set.
func (o *ExceptionInfo) GetExcepsOk() ([]Exception, bool) {
	if o == nil {
		return nil, false
	}
	return o.Exceps, true
}

// SetExceps sets field value
func (o *ExceptionInfo) SetExceps(v []Exception) {
	o.Exceps = v
}

func (o ExceptionInfo) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.IpTrafficFilter) {
		toSerialize["ipTrafficFilter"] = o.IpTrafficFilter
	}
	if !openapi.IsNil(o.EthTrafficFilter) {
		toSerialize["ethTrafficFilter"] = o.EthTrafficFilter
	}
	toSerialize["exceps"] = o.Exceps
	return toSerialize, nil
}

type NullableExceptionInfo struct {
	value *ExceptionInfo
	isSet bool
}

func (v NullableExceptionInfo) Get() *ExceptionInfo {
	return v.value
}

func (v *NullableExceptionInfo) Set(val *ExceptionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableExceptionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableExceptionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExceptionInfo(val *ExceptionInfo) *NullableExceptionInfo {
	return &NullableExceptionInfo{value: val, isSet: true}
}

func (v NullableExceptionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExceptionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
