// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// ReportTypeMdt The enumeration ReportTypeMdt defines Report Type for logged MDT in the trace. See 3GPP TS 32.422 for further description of the values. It shall comply with the provisions defined in table 5.6.3.4-1.
type ReportTypeMdt string

// List of ReportTypeMdt
const (
	REPORTTYPEMDT_PERIODICAL    ReportTypeMdt = "PERIODICAL"
	REPORTTYPEMDT_EVENT_TRIGGED ReportTypeMdt = "EVENT_TRIGGED"
)

// All allowed values of ReportTypeMdt enum
var AllowedReportTypeMdtEnumValues = []ReportTypeMdt{
	"PERIODICAL",
	"EVENT_TRIGGED",
}

func (v *ReportTypeMdt) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ReportTypeMdt(value)
	if slices.Contains(AllowedReportTypeMdtEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid ReportTypeMdt", value)
}

// NewReportTypeMdtFromValue returns a pointer to a valid ReportTypeMdt
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewReportTypeMdtFromValue(v string) (*ReportTypeMdt, error) {
	ev := ReportTypeMdt(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for ReportTypeMdt: valid values are %v", v, AllowedReportTypeMdtEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ReportTypeMdt) IsValid() bool {
	return slices.Contains(AllowedReportTypeMdtEnumValues, v)
}

// Ptr returns reference to ReportTypeMdt value
func (v ReportTypeMdt) Ptr() *ReportTypeMdt {
	return &v
}

type NullableReportTypeMdt struct {
	value *ReportTypeMdt
	isSet bool
}

func (v NullableReportTypeMdt) Get() *ReportTypeMdt {
	return v.value
}

func (v *NullableReportTypeMdt) Set(val *ReportTypeMdt) {
	v.value = val
	v.isSet = true
}

func (v NullableReportTypeMdt) IsSet() bool {
	return v.isSet
}

func (v *NullableReportTypeMdt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportTypeMdt(val *ReportTypeMdt) *NullableReportTypeMdt {
	return &NullableReportTypeMdt{value: val, isSet: true}
}

func (v NullableReportTypeMdt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportTypeMdt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
