// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// LocationFilter Describes the supported filters of LOCATION_REPORT event type
type LocationFilter string

// List of LocationFilter
const (
	LOCATIONFILTER_TAI      LocationFilter = "TAI"
	LOCATIONFILTER_CELL_ID  LocationFilter = "CELL_ID"
	LOCATIONFILTER_RAN_NODE LocationFilter = "RAN_NODE"
	LOCATIONFILTER_N3_IWF   LocationFilter = "N3IWF"
	LOCATIONFILTER_UE_IP    LocationFilter = "UE_IP"
	LOCATIONFILTER_UDP_PORT LocationFilter = "UDP_PORT"
	LOCATIONFILTER_TNAP_ID  LocationFilter = "TNAP_ID"
	LOCATIONFILTER_GLI      LocationFilter = "GLI"
	LOCATIONFILTER_TWAP_ID  LocationFilter = "TWAP_ID"
)

// All allowed values of LocationFilter enum
var AllowedLocationFilterEnumValues = []LocationFilter{
	"TAI",
	"CELL_ID",
	"RAN_NODE",
	"N3IWF",
	"UE_IP",
	"UDP_PORT",
	"TNAP_ID",
	"GLI",
	"TWAP_ID",
}

func (v *LocationFilter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LocationFilter(value)
	if slices.Contains(AllowedLocationFilterEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid LocationFilter", value)
}

// NewLocationFilterFromValue returns a pointer to a valid LocationFilter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLocationFilterFromValue(v string) (*LocationFilter, error) {
	ev := LocationFilter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for LocationFilter: valid values are %v", v, AllowedLocationFilterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LocationFilter) IsValid() bool {
	return slices.Contains(AllowedLocationFilterEnumValues, v)
}

// Ptr returns reference to LocationFilter value
func (v LocationFilter) Ptr() *LocationFilter {
	return &v
}

type NullableLocationFilter struct {
	value *LocationFilter
	isSet bool
}

func (v NullableLocationFilter) Get() *LocationFilter {
	return v.value
}

func (v *NullableLocationFilter) Set(val *LocationFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationFilter(val *LocationFilter) *NullableLocationFilter {
	return &NullableLocationFilter{value: val, isSet: true}
}

func (v NullableLocationFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
