// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Npcf_PolicyAuthorization Service API

PCF Policy Authorization Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the QosMonitoringReportPcf type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &QosMonitoringReportPcf{}

// QosMonitoringReportPcf QoS Monitoring reporting information.
type QosMonitoringReportPcf struct {
	Flows    []Flows `json:"flows,omitempty" yaml:"flows,omitempty"`
	UlDelays []int32 `json:"ulDelays,omitempty" yaml:"ulDelays,omitempty"`
	DlDelays []int32 `json:"dlDelays,omitempty" yaml:"dlDelays,omitempty"`
	RtDelays []int32 `json:"rtDelays,omitempty" yaml:"rtDelays,omitempty"`
	// Represents the packet delay measurement failure indicator.
	Pdmf      *bool   `json:"pdmf,omitempty" yaml:"pdmf,omitempty"`
	UlConInfo []int32 `json:"ulConInfo,omitempty" yaml:"ulConInfo,omitempty"`
	DlConInfo []int32 `json:"dlConInfo,omitempty" yaml:"dlConInfo,omitempty"`
	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\".
	UlDataRate *string `json:"ulDataRate,omitempty" yaml:"ulDataRate,omitempty" validate:"regexp=^\\\\d+(\\\\.\\\\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$"`
	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\".
	DlDataRate *string `json:"dlDataRate,omitempty" yaml:"dlDataRate,omitempty" validate:"regexp=^\\\\d+(\\\\.\\\\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$"`
}

// NewQosMonitoringReportPcf instantiates a new QosMonitoringReportPcf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQosMonitoringReportPcf() *QosMonitoringReportPcf {
	this := QosMonitoringReportPcf{}
	return &this
}

// NewQosMonitoringReportPcfWithDefaults instantiates a new QosMonitoringReportPcf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQosMonitoringReportPcfWithDefaults() *QosMonitoringReportPcf {
	this := QosMonitoringReportPcf{}
	return &this
}

// GetFlows returns the Flows field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetFlows() []Flows {
	if o == nil || openapi.IsNil(o.Flows) {
		var ret []Flows
		return ret
	}
	return o.Flows
}

// GetFlowsOk returns a tuple with the Flows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetFlowsOk() ([]Flows, bool) {
	if o == nil || openapi.IsNil(o.Flows) {
		return nil, false
	}
	return o.Flows, true
}

// HasFlows returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasFlows() bool {
	if o != nil && !openapi.IsNil(o.Flows) {
		return true
	}

	return false
}

// SetFlows gets a reference to the given []Flows and assigns it to the Flows field.
func (o *QosMonitoringReportPcf) SetFlows(v []Flows) {
	o.Flows = v
}

// GetUlDelays returns the UlDelays field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetUlDelays() []int32 {
	if o == nil || openapi.IsNil(o.UlDelays) {
		var ret []int32
		return ret
	}
	return o.UlDelays
}

// GetUlDelaysOk returns a tuple with the UlDelays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetUlDelaysOk() ([]int32, bool) {
	if o == nil || openapi.IsNil(o.UlDelays) {
		return nil, false
	}
	return o.UlDelays, true
}

// HasUlDelays returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasUlDelays() bool {
	if o != nil && !openapi.IsNil(o.UlDelays) {
		return true
	}

	return false
}

// SetUlDelays gets a reference to the given []int32 and assigns it to the UlDelays field.
func (o *QosMonitoringReportPcf) SetUlDelays(v []int32) {
	o.UlDelays = v
}

// GetDlDelays returns the DlDelays field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetDlDelays() []int32 {
	if o == nil || openapi.IsNil(o.DlDelays) {
		var ret []int32
		return ret
	}
	return o.DlDelays
}

// GetDlDelaysOk returns a tuple with the DlDelays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetDlDelaysOk() ([]int32, bool) {
	if o == nil || openapi.IsNil(o.DlDelays) {
		return nil, false
	}
	return o.DlDelays, true
}

// HasDlDelays returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasDlDelays() bool {
	if o != nil && !openapi.IsNil(o.DlDelays) {
		return true
	}

	return false
}

// SetDlDelays gets a reference to the given []int32 and assigns it to the DlDelays field.
func (o *QosMonitoringReportPcf) SetDlDelays(v []int32) {
	o.DlDelays = v
}

// GetRtDelays returns the RtDelays field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetRtDelays() []int32 {
	if o == nil || openapi.IsNil(o.RtDelays) {
		var ret []int32
		return ret
	}
	return o.RtDelays
}

// GetRtDelaysOk returns a tuple with the RtDelays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetRtDelaysOk() ([]int32, bool) {
	if o == nil || openapi.IsNil(o.RtDelays) {
		return nil, false
	}
	return o.RtDelays, true
}

// HasRtDelays returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasRtDelays() bool {
	if o != nil && !openapi.IsNil(o.RtDelays) {
		return true
	}

	return false
}

// SetRtDelays gets a reference to the given []int32 and assigns it to the RtDelays field.
func (o *QosMonitoringReportPcf) SetRtDelays(v []int32) {
	o.RtDelays = v
}

// GetPdmf returns the Pdmf field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetPdmf() bool {
	if o == nil || openapi.IsNil(o.Pdmf) {
		var ret bool
		return ret
	}
	return *o.Pdmf
}

// GetPdmfOk returns a tuple with the Pdmf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetPdmfOk() (*bool, bool) {
	if o == nil || openapi.IsNil(o.Pdmf) {
		return nil, false
	}
	return o.Pdmf, true
}

// HasPdmf returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasPdmf() bool {
	if o != nil && !openapi.IsNil(o.Pdmf) {
		return true
	}

	return false
}

// SetPdmf gets a reference to the given bool and assigns it to the Pdmf field.
func (o *QosMonitoringReportPcf) SetPdmf(v bool) {
	o.Pdmf = &v
}

// GetUlConInfo returns the UlConInfo field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetUlConInfo() []int32 {
	if o == nil || openapi.IsNil(o.UlConInfo) {
		var ret []int32
		return ret
	}
	return o.UlConInfo
}

// GetUlConInfoOk returns a tuple with the UlConInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetUlConInfoOk() ([]int32, bool) {
	if o == nil || openapi.IsNil(o.UlConInfo) {
		return nil, false
	}
	return o.UlConInfo, true
}

// HasUlConInfo returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasUlConInfo() bool {
	if o != nil && !openapi.IsNil(o.UlConInfo) {
		return true
	}

	return false
}

// SetUlConInfo gets a reference to the given []int32 and assigns it to the UlConInfo field.
func (o *QosMonitoringReportPcf) SetUlConInfo(v []int32) {
	o.UlConInfo = v
}

// GetDlConInfo returns the DlConInfo field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetDlConInfo() []int32 {
	if o == nil || openapi.IsNil(o.DlConInfo) {
		var ret []int32
		return ret
	}
	return o.DlConInfo
}

// GetDlConInfoOk returns a tuple with the DlConInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetDlConInfoOk() ([]int32, bool) {
	if o == nil || openapi.IsNil(o.DlConInfo) {
		return nil, false
	}
	return o.DlConInfo, true
}

// HasDlConInfo returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasDlConInfo() bool {
	if o != nil && !openapi.IsNil(o.DlConInfo) {
		return true
	}

	return false
}

// SetDlConInfo gets a reference to the given []int32 and assigns it to the DlConInfo field.
func (o *QosMonitoringReportPcf) SetDlConInfo(v []int32) {
	o.DlConInfo = v
}

// GetUlDataRate returns the UlDataRate field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetUlDataRate() string {
	if o == nil || openapi.IsNil(o.UlDataRate) {
		var ret string
		return ret
	}
	return *o.UlDataRate
}

// GetUlDataRateOk returns a tuple with the UlDataRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetUlDataRateOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.UlDataRate) {
		return nil, false
	}
	return o.UlDataRate, true
}

// HasUlDataRate returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasUlDataRate() bool {
	if o != nil && !openapi.IsNil(o.UlDataRate) {
		return true
	}

	return false
}

// SetUlDataRate gets a reference to the given string and assigns it to the UlDataRate field.
func (o *QosMonitoringReportPcf) SetUlDataRate(v string) {
	o.UlDataRate = &v
}

// GetDlDataRate returns the DlDataRate field value if set, zero value otherwise.
func (o *QosMonitoringReportPcf) GetDlDataRate() string {
	if o == nil || openapi.IsNil(o.DlDataRate) {
		var ret string
		return ret
	}
	return *o.DlDataRate
}

// GetDlDataRateOk returns a tuple with the DlDataRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QosMonitoringReportPcf) GetDlDataRateOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.DlDataRate) {
		return nil, false
	}
	return o.DlDataRate, true
}

// HasDlDataRate returns a boolean if a field has been set.
func (o *QosMonitoringReportPcf) HasDlDataRate() bool {
	if o != nil && !openapi.IsNil(o.DlDataRate) {
		return true
	}

	return false
}

// SetDlDataRate gets a reference to the given string and assigns it to the DlDataRate field.
func (o *QosMonitoringReportPcf) SetDlDataRate(v string) {
	o.DlDataRate = &v
}

func (o QosMonitoringReportPcf) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.Flows) {
		toSerialize["flows"] = o.Flows
	}
	if !openapi.IsNil(o.UlDelays) {
		toSerialize["ulDelays"] = o.UlDelays
	}
	if !openapi.IsNil(o.DlDelays) {
		toSerialize["dlDelays"] = o.DlDelays
	}
	if !openapi.IsNil(o.RtDelays) {
		toSerialize["rtDelays"] = o.RtDelays
	}
	if !openapi.IsNil(o.Pdmf) {
		toSerialize["pdmf"] = o.Pdmf
	}
	if !openapi.IsNil(o.UlConInfo) {
		toSerialize["ulConInfo"] = o.UlConInfo
	}
	if !openapi.IsNil(o.DlConInfo) {
		toSerialize["dlConInfo"] = o.DlConInfo
	}
	if !openapi.IsNil(o.UlDataRate) {
		toSerialize["ulDataRate"] = o.UlDataRate
	}
	if !openapi.IsNil(o.DlDataRate) {
		toSerialize["dlDataRate"] = o.DlDataRate
	}
	return toSerialize, nil
}

type NullableQosMonitoringReportPcf struct {
	value *QosMonitoringReportPcf
	isSet bool
}

func (v NullableQosMonitoringReportPcf) Get() *QosMonitoringReportPcf {
	return v.value
}

func (v *NullableQosMonitoringReportPcf) Set(val *QosMonitoringReportPcf) {
	v.value = val
	v.isSet = true
}

func (v NullableQosMonitoringReportPcf) IsSet() bool {
	return v.isSet
}

func (v *NullableQosMonitoringReportPcf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQosMonitoringReportPcf(val *QosMonitoringReportPcf) *NullableQosMonitoringReportPcf {
	return &NullableQosMonitoringReportPcf{value: val, isSet: true}
}

func (v NullableQosMonitoringReportPcf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQosMonitoringReportPcf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
