// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"time"

	"github.com/omec-project/openapi/v2"
)

// checks if the AuthorizationData type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &AuthorizationData{}

// AuthorizationData NIDD Authorization Information
type AuthorizationData struct {
	AuthorizationData   []UserIdentifier                                          `json:"authorizationData" yaml:"authorizationData"`
	AllowedDnnList      []AccessAndMobilitySubscriptionDataSubscribedDnnListInner `json:"allowedDnnList,omitempty" yaml:"allowedDnnList,omitempty"`
	AllowedSnssaiList   []Snssai                                                  `json:"allowedSnssaiList,omitempty" yaml:"allowedSnssaiList,omitempty"`
	AllowedMtcProviders []MtcProvider                                             `json:"allowedMtcProviders,omitempty" yaml:"allowedMtcProviders,omitempty"`
	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime *time.Time `json:"validityTime,omitempty" yaml:"validityTime,omitempty"`
}

// NewAuthorizationData instantiates a new AuthorizationData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthorizationData(authorizationData []UserIdentifier) *AuthorizationData {
	this := AuthorizationData{}
	this.AuthorizationData = authorizationData
	return &this
}

// NewAuthorizationDataWithDefaults instantiates a new AuthorizationData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthorizationDataWithDefaults() *AuthorizationData {
	this := AuthorizationData{}
	return &this
}

// GetAuthorizationData returns the AuthorizationData field value
func (o *AuthorizationData) GetAuthorizationData() []UserIdentifier {
	if o == nil {
		var ret []UserIdentifier
		return ret
	}

	return o.AuthorizationData
}

// GetAuthorizationDataOk returns a tuple with the AuthorizationData field value
// and a boolean to check if the value has been set.
func (o *AuthorizationData) GetAuthorizationDataOk() ([]UserIdentifier, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthorizationData, true
}

// SetAuthorizationData sets field value
func (o *AuthorizationData) SetAuthorizationData(v []UserIdentifier) {
	o.AuthorizationData = v
}

// GetAllowedDnnList returns the AllowedDnnList field value if set, zero value otherwise.
func (o *AuthorizationData) GetAllowedDnnList() []AccessAndMobilitySubscriptionDataSubscribedDnnListInner {
	if o == nil || openapi.IsNil(o.AllowedDnnList) {
		var ret []AccessAndMobilitySubscriptionDataSubscribedDnnListInner
		return ret
	}
	return o.AllowedDnnList
}

// GetAllowedDnnListOk returns a tuple with the AllowedDnnList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationData) GetAllowedDnnListOk() ([]AccessAndMobilitySubscriptionDataSubscribedDnnListInner, bool) {
	if o == nil || openapi.IsNil(o.AllowedDnnList) {
		return nil, false
	}
	return o.AllowedDnnList, true
}

// HasAllowedDnnList returns a boolean if a field has been set.
func (o *AuthorizationData) HasAllowedDnnList() bool {
	if o != nil && !openapi.IsNil(o.AllowedDnnList) {
		return true
	}

	return false
}

// SetAllowedDnnList gets a reference to the given []AccessAndMobilitySubscriptionDataSubscribedDnnListInner and assigns it to the AllowedDnnList field.
func (o *AuthorizationData) SetAllowedDnnList(v []AccessAndMobilitySubscriptionDataSubscribedDnnListInner) {
	o.AllowedDnnList = v
}

// GetAllowedSnssaiList returns the AllowedSnssaiList field value if set, zero value otherwise.
func (o *AuthorizationData) GetAllowedSnssaiList() []Snssai {
	if o == nil || openapi.IsNil(o.AllowedSnssaiList) {
		var ret []Snssai
		return ret
	}
	return o.AllowedSnssaiList
}

// GetAllowedSnssaiListOk returns a tuple with the AllowedSnssaiList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationData) GetAllowedSnssaiListOk() ([]Snssai, bool) {
	if o == nil || openapi.IsNil(o.AllowedSnssaiList) {
		return nil, false
	}
	return o.AllowedSnssaiList, true
}

// HasAllowedSnssaiList returns a boolean if a field has been set.
func (o *AuthorizationData) HasAllowedSnssaiList() bool {
	if o != nil && !openapi.IsNil(o.AllowedSnssaiList) {
		return true
	}

	return false
}

// SetAllowedSnssaiList gets a reference to the given []Snssai and assigns it to the AllowedSnssaiList field.
func (o *AuthorizationData) SetAllowedSnssaiList(v []Snssai) {
	o.AllowedSnssaiList = v
}

// GetAllowedMtcProviders returns the AllowedMtcProviders field value if set, zero value otherwise.
func (o *AuthorizationData) GetAllowedMtcProviders() []MtcProvider {
	if o == nil || openapi.IsNil(o.AllowedMtcProviders) {
		var ret []MtcProvider
		return ret
	}
	return o.AllowedMtcProviders
}

// GetAllowedMtcProvidersOk returns a tuple with the AllowedMtcProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationData) GetAllowedMtcProvidersOk() ([]MtcProvider, bool) {
	if o == nil || openapi.IsNil(o.AllowedMtcProviders) {
		return nil, false
	}
	return o.AllowedMtcProviders, true
}

// HasAllowedMtcProviders returns a boolean if a field has been set.
func (o *AuthorizationData) HasAllowedMtcProviders() bool {
	if o != nil && !openapi.IsNil(o.AllowedMtcProviders) {
		return true
	}

	return false
}

// SetAllowedMtcProviders gets a reference to the given []MtcProvider and assigns it to the AllowedMtcProviders field.
func (o *AuthorizationData) SetAllowedMtcProviders(v []MtcProvider) {
	o.AllowedMtcProviders = v
}

// GetValidityTime returns the ValidityTime field value if set, zero value otherwise.
func (o *AuthorizationData) GetValidityTime() time.Time {
	if o == nil || openapi.IsNil(o.ValidityTime) {
		var ret time.Time
		return ret
	}
	return *o.ValidityTime
}

// GetValidityTimeOk returns a tuple with the ValidityTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthorizationData) GetValidityTimeOk() (*time.Time, bool) {
	if o == nil || openapi.IsNil(o.ValidityTime) {
		return nil, false
	}
	return o.ValidityTime, true
}

// HasValidityTime returns a boolean if a field has been set.
func (o *AuthorizationData) HasValidityTime() bool {
	if o != nil && !openapi.IsNil(o.ValidityTime) {
		return true
	}

	return false
}

// SetValidityTime gets a reference to the given time.Time and assigns it to the ValidityTime field.
func (o *AuthorizationData) SetValidityTime(v time.Time) {
	o.ValidityTime = &v
}

func (o AuthorizationData) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	toSerialize["authorizationData"] = o.AuthorizationData
	if !openapi.IsNil(o.AllowedDnnList) {
		toSerialize["allowedDnnList"] = o.AllowedDnnList
	}
	if !openapi.IsNil(o.AllowedSnssaiList) {
		toSerialize["allowedSnssaiList"] = o.AllowedSnssaiList
	}
	if !openapi.IsNil(o.AllowedMtcProviders) {
		toSerialize["allowedMtcProviders"] = o.AllowedMtcProviders
	}
	if !openapi.IsNil(o.ValidityTime) {
		toSerialize["validityTime"] = o.ValidityTime
	}
	return toSerialize, nil
}

type NullableAuthorizationData struct {
	value *AuthorizationData
	isSet bool
}

func (v NullableAuthorizationData) Get() *AuthorizationData {
	return v.value
}

func (v *NullableAuthorizationData) Set(val *AuthorizationData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthorizationData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthorizationData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthorizationData(val *AuthorizationData) *NullableAuthorizationData {
	return &NullableAuthorizationData{value: val, isSet: true}
}

func (v NullableAuthorizationData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthorizationData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
