// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the PointUncertaintyCircle type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &PointUncertaintyCircle{}

// PointUncertaintyCircle Ellipsoid point with uncertainty circle.
type PointUncertaintyCircle struct {
	GADShape
	Point *GeographicalCoordinates `json:"point,omitempty" yaml:"point,omitempty"`
	// Indicates value of uncertainty.
	Uncertainty *float32 `json:"uncertainty,omitempty" yaml:"uncertainty,omitempty"`
}

// NewPointUncertaintyCircle instantiates a new PointUncertaintyCircle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointUncertaintyCircle(shape SupportedGADShapes) *PointUncertaintyCircle {
	this := PointUncertaintyCircle{}
	this.Shape = shape
	return &this
}

// NewPointUncertaintyCircleWithDefaults instantiates a new PointUncertaintyCircle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointUncertaintyCircleWithDefaults() *PointUncertaintyCircle {
	this := PointUncertaintyCircle{}
	return &this
}

// GetPoint returns the Point field value if set, zero value otherwise.
func (o *PointUncertaintyCircle) GetPoint() GeographicalCoordinates {
	if o == nil || openapi.IsNil(o.Point) {
		var ret GeographicalCoordinates
		return ret
	}
	return *o.Point
}

// GetPointOk returns a tuple with the Point field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUncertaintyCircle) GetPointOk() (*GeographicalCoordinates, bool) {
	if o == nil || openapi.IsNil(o.Point) {
		return nil, false
	}
	return o.Point, true
}

// HasPoint returns a boolean if a field has been set.
func (o *PointUncertaintyCircle) HasPoint() bool {
	if o != nil && !openapi.IsNil(o.Point) {
		return true
	}

	return false
}

// SetPoint gets a reference to the given GeographicalCoordinates and assigns it to the Point field.
func (o *PointUncertaintyCircle) SetPoint(v GeographicalCoordinates) {
	o.Point = &v
}

// GetUncertainty returns the Uncertainty field value if set, zero value otherwise.
func (o *PointUncertaintyCircle) GetUncertainty() float32 {
	if o == nil || openapi.IsNil(o.Uncertainty) {
		var ret float32
		return ret
	}
	return *o.Uncertainty
}

// GetUncertaintyOk returns a tuple with the Uncertainty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PointUncertaintyCircle) GetUncertaintyOk() (*float32, bool) {
	if o == nil || openapi.IsNil(o.Uncertainty) {
		return nil, false
	}
	return o.Uncertainty, true
}

// HasUncertainty returns a boolean if a field has been set.
func (o *PointUncertaintyCircle) HasUncertainty() bool {
	if o != nil && !openapi.IsNil(o.Uncertainty) {
		return true
	}

	return false
}

// SetUncertainty gets a reference to the given float32 and assigns it to the Uncertainty field.
func (o *PointUncertaintyCircle) SetUncertainty(v float32) {
	o.Uncertainty = &v
}

func (o PointUncertaintyCircle) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	serializedGADShape, errGADShape := json.Marshal(o.GADShape)
	if errGADShape != nil {
		return map[string]any{}, errGADShape
	}
	errGADShape = json.Unmarshal([]byte(serializedGADShape), &toSerialize)
	if errGADShape != nil {
		return map[string]any{}, errGADShape
	}
	if !openapi.IsNil(o.Point) {
		toSerialize["point"] = o.Point
	}
	if !openapi.IsNil(o.Uncertainty) {
		toSerialize["uncertainty"] = o.Uncertainty
	}
	return toSerialize, nil
}

type NullablePointUncertaintyCircle struct {
	value *PointUncertaintyCircle
	isSet bool
}

func (v NullablePointUncertaintyCircle) Get() *PointUncertaintyCircle {
	return v.value
}

func (v *NullablePointUncertaintyCircle) Set(val *PointUncertaintyCircle) {
	v.value = val
	v.isSet = true
}

func (v NullablePointUncertaintyCircle) IsSet() bool {
	return v.isSet
}

func (v *NullablePointUncertaintyCircle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointUncertaintyCircle(val *PointUncertaintyCircle) *NullablePointUncertaintyCircle {
	return &NullablePointUncertaintyCircle{value: val, isSet: true}
}

func (v NullablePointUncertaintyCircle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointUncertaintyCircle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
