// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// PduSessionStatusUdr Represents the state of the PDU session.   Possible values are - \"ACTIVE\": the PDU session is active. - \"RELEASED\": the PDU session released.
type PduSessionStatusUdr string

// List of PduSessionStatusUdr
const (
	PDUSESSIONSTATUSUDR_ACTIVE   PduSessionStatusUdr = "ACTIVE"
	PDUSESSIONSTATUSUDR_RELEASED PduSessionStatusUdr = "RELEASED"
)

// All allowed values of PduSessionStatusUdr enum
var AllowedPduSessionStatusUdrEnumValues = []PduSessionStatusUdr{
	"ACTIVE",
	"RELEASED",
}

func (v *PduSessionStatusUdr) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PduSessionStatusUdr(value)
	if slices.Contains(AllowedPduSessionStatusUdrEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid PduSessionStatusUdr", value)
}

// NewPduSessionStatusUdrFromValue returns a pointer to a valid PduSessionStatusUdr
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPduSessionStatusUdrFromValue(v string) (*PduSessionStatusUdr, error) {
	ev := PduSessionStatusUdr(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for PduSessionStatusUdr: valid values are %v", v, AllowedPduSessionStatusUdrEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PduSessionStatusUdr) IsValid() bool {
	return slices.Contains(AllowedPduSessionStatusUdrEnumValues, v)
}

// Ptr returns reference to PduSessionStatusUdr value
func (v PduSessionStatusUdr) Ptr() *PduSessionStatusUdr {
	return &v
}

type NullablePduSessionStatusUdr struct {
	value *PduSessionStatusUdr
	isSet bool
}

func (v NullablePduSessionStatusUdr) Get() *PduSessionStatusUdr {
	return v.value
}

func (v *NullablePduSessionStatusUdr) Set(val *PduSessionStatusUdr) {
	v.value = val
	v.isSet = true
}

func (v NullablePduSessionStatusUdr) IsSet() bool {
	return v.isSet
}

func (v *NullablePduSessionStatusUdr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePduSessionStatusUdr(val *PduSessionStatusUdr) *NullablePduSessionStatusUdr {
	return &NullablePduSessionStatusUdr{value: val, isSet: true}
}

func (v NullablePduSessionStatusUdr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePduSessionStatusUdr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
