// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// SmsSupport Indicates the supported SMS delivery of a UE
type SmsSupport string

// List of SmsSupport
const (
	SMSSUPPORT__3_GPP    SmsSupport = "3GPP"
	SMSSUPPORT_NON_3_GPP SmsSupport = "NON_3GPP"
	SMSSUPPORT_BOTH      SmsSupport = "BOTH"
	SMSSUPPORT_NONE      SmsSupport = "NONE"
)

// All allowed values of SmsSupport enum
var AllowedSmsSupportEnumValues = []SmsSupport{
	"3GPP",
	"NON_3GPP",
	"BOTH",
	"NONE",
}

func (v *SmsSupport) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SmsSupport(value)
	if slices.Contains(AllowedSmsSupportEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid SmsSupport", value)
}

// NewSmsSupportFromValue returns a pointer to a valid SmsSupport
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSmsSupportFromValue(v string) (*SmsSupport, error) {
	ev := SmsSupport(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for SmsSupport: valid values are %v", v, AllowedSmsSupportEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SmsSupport) IsValid() bool {
	return slices.Contains(AllowedSmsSupportEnumValues, v)
}

// Ptr returns reference to SmsSupport value
func (v SmsSupport) Ptr() *SmsSupport {
	return &v
}

type NullableSmsSupport struct {
	value *SmsSupport
	isSet bool
}

func (v NullableSmsSupport) Get() *SmsSupport {
	return v.value
}

func (v *NullableSmsSupport) Set(val *SmsSupport) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsSupport) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsSupport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsSupport(val *SmsSupport) *NullableSmsSupport {
	return &NullableSmsSupport{value: val, isSet: true}
}

func (v NullableSmsSupport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsSupport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
