// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the SnssaiSmfInfoItem type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &SnssaiSmfInfoItem{}

// SnssaiSmfInfoItem Set of parameters supported by SMF for a given S-NSSAI
type SnssaiSmfInfoItem struct {
	SNssai           Snssai
	DnnSmfInfoList   []DnnSmfInfoItem
	DnnSmfInfoListId *int32
}

// NewSnssaiSmfInfoItem instantiates a new SnssaiSmfInfoItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSnssaiSmfInfoItem(sNssai Snssai) *SnssaiSmfInfoItem {
	this := SnssaiSmfInfoItem{}
	return &this
}

// NewSnssaiSmfInfoItemWithDefaults instantiates a new SnssaiSmfInfoItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSnssaiSmfInfoItemWithDefaults() *SnssaiSmfInfoItem {
	this := SnssaiSmfInfoItem{}
	return &this
}

// GetSNssai returns the SNssai field value
func (o *SnssaiSmfInfoItem) GetSNssai() Snssai {
	if o == nil {
		var ret Snssai
		return ret
	}

	return o.SNssai
}

// GetSNssaiOk returns a tuple with the SNssai field value
// and a boolean to check if the value has been set.
func (o *SnssaiSmfInfoItem) GetSNssaiOk() (*Snssai, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SNssai, true
}

// SetSNssai sets field value
func (o *SnssaiSmfInfoItem) SetSNssai(v Snssai) {
	o.SNssai = v
}

// GetDnnSmfInfoList returns the DnnSmfInfoList field value if set, zero value otherwise.
func (o *SnssaiSmfInfoItem) GetDnnSmfInfoList() []DnnSmfInfoItem {
	if o == nil || openapi.IsNil(o.DnnSmfInfoList) {
		var ret []DnnSmfInfoItem
		return ret
	}
	return o.DnnSmfInfoList
}

// GetDnnSmfInfoListOk returns a tuple with the DnnSmfInfoList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnssaiSmfInfoItem) GetDnnSmfInfoListOk() ([]DnnSmfInfoItem, bool) {
	if o == nil || openapi.IsNil(o.DnnSmfInfoList) {
		return nil, false
	}
	return o.DnnSmfInfoList, true
}

// HasDnnSmfInfoList returns a boolean if a field has been set.
func (o *SnssaiSmfInfoItem) HasDnnSmfInfoList() bool {
	if o != nil && !openapi.IsNil(o.DnnSmfInfoList) {
		return true
	}

	return false
}

// SetDnnSmfInfoList gets a reference to the given []DnnSmfInfoItem and assigns it to the DnnSmfInfoList field.
func (o *SnssaiSmfInfoItem) SetDnnSmfInfoList(v []DnnSmfInfoItem) {
	o.DnnSmfInfoList = v
}

// GetDnnSmfInfoListId returns the DnnSmfInfoListId field value if set, zero value otherwise.
func (o *SnssaiSmfInfoItem) GetDnnSmfInfoListId() int32 {
	if o == nil || openapi.IsNil(o.DnnSmfInfoListId) {
		var ret int32
		return ret
	}
	return *o.DnnSmfInfoListId
}

// GetDnnSmfInfoListIdOk returns a tuple with the DnnSmfInfoListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SnssaiSmfInfoItem) GetDnnSmfInfoListIdOk() (*int32, bool) {
	if o == nil || openapi.IsNil(o.DnnSmfInfoListId) {
		return nil, false
	}
	return o.DnnSmfInfoListId, true
}

// HasDnnSmfInfoListId returns a boolean if a field has been set.
func (o *SnssaiSmfInfoItem) HasDnnSmfInfoListId() bool {
	if o != nil && !openapi.IsNil(o.DnnSmfInfoListId) {
		return true
	}

	return false
}

// SetDnnSmfInfoListId gets a reference to the given int32 and assigns it to the DnnSmfInfoListId field.
func (o *SnssaiSmfInfoItem) SetDnnSmfInfoListId(v int32) {
	o.DnnSmfInfoListId = &v
}

func (o SnssaiSmfInfoItem) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	toSerialize["sNssai"] = o.SNssai
	if !openapi.IsNil(o.DnnSmfInfoList) {
		toSerialize["dnnSmfInfoList"] = o.DnnSmfInfoList
	}
	if !openapi.IsNil(o.DnnSmfInfoListId) {
		toSerialize["dnnSmfInfoListId"] = o.DnnSmfInfoListId
	}
	return toSerialize, nil
}

type NullableSnssaiSmfInfoItem struct {
	value *SnssaiSmfInfoItem
	isSet bool
}

func (v NullableSnssaiSmfInfoItem) Get() *SnssaiSmfInfoItem {
	return v.value
}

func (v *NullableSnssaiSmfInfoItem) Set(val *SnssaiSmfInfoItem) {
	v.value = val
	v.isSet = true
}

func (v NullableSnssaiSmfInfoItem) IsSet() bool {
	return v.isSet
}

func (v *NullableSnssaiSmfInfoItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSnssaiSmfInfoItem(val *SnssaiSmfInfoItem) *NullableSnssaiSmfInfoItem {
	return &NullableSnssaiSmfInfoItem{value: val, isSet: true}
}

func (v NullableSnssaiSmfInfoItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSnssaiSmfInfoItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
