// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// NsacAdmissionMode Indicates the NSAC admission mode applied in roaming case.
type NsacAdmissionMode string

// List of NsacAdmissionMode
const (
	NSACADMISSIONMODE_VPLMN_ADMISSION             NsacAdmissionMode = "VPLMN_ADMISSION"
	NSACADMISSIONMODE_VPLMN_WITH_HPLMN_ASSISTANCE NsacAdmissionMode = "VPLMN_WITH_HPLMN_ASSISTANCE"
	NSACADMISSIONMODE_HPLMN_ADMISSION             NsacAdmissionMode = "HPLMN_ADMISSION"
)

// All allowed values of NsacAdmissionMode enum
var AllowedNsacAdmissionModeEnumValues = []NsacAdmissionMode{
	"VPLMN_ADMISSION",
	"VPLMN_WITH_HPLMN_ASSISTANCE",
	"HPLMN_ADMISSION",
}

func (v *NsacAdmissionMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NsacAdmissionMode(value)
	if slices.Contains(AllowedNsacAdmissionModeEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid NsacAdmissionMode", value)
}

// NewNsacAdmissionModeFromValue returns a pointer to a valid NsacAdmissionMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNsacAdmissionModeFromValue(v string) (*NsacAdmissionMode, error) {
	ev := NsacAdmissionMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for NsacAdmissionMode: valid values are %v", v, AllowedNsacAdmissionModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NsacAdmissionMode) IsValid() bool {
	return slices.Contains(AllowedNsacAdmissionModeEnumValues, v)
}

// Ptr returns reference to NsacAdmissionMode value
func (v NsacAdmissionMode) Ptr() *NsacAdmissionMode {
	return &v
}

type NullableNsacAdmissionMode struct {
	value *NsacAdmissionMode
	isSet bool
}

func (v NullableNsacAdmissionMode) Get() *NsacAdmissionMode {
	return v.value
}

func (v *NullableNsacAdmissionMode) Set(val *NsacAdmissionMode) {
	v.value = val
	v.isSet = true
}

func (v NullableNsacAdmissionMode) IsSet() bool {
	return v.isSet
}

func (v *NullableNsacAdmissionMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNsacAdmissionMode(val *NsacAdmissionMode) *NullableNsacAdmissionMode {
	return &NullableNsacAdmissionMode{value: val, isSet: true}
}

func (v NullableNsacAdmissionMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNsacAdmissionMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
