// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudm_SDM

Nudm Subscriber Data Management Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the UeContextInSmsfData type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &UeContextInSmsfData{}

// UeContextInSmsfData struct for UeContextInSmsfData
type UeContextInSmsfData struct {
	SmsfInfo3GppAccess    *SmsfInfoUdm `json:"smsfInfo3GppAccess,omitempty" yaml:"smsfInfo3GppAccess,omitempty"`
	SmsfInfoNon3GppAccess *SmsfInfoUdm `json:"smsfInfoNon3GppAccess,omitempty" yaml:"smsfInfoNon3GppAccess,omitempty"`
}

// NewUeContextInSmsfData instantiates a new UeContextInSmsfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUeContextInSmsfData() *UeContextInSmsfData {
	this := UeContextInSmsfData{}
	return &this
}

// NewUeContextInSmsfDataWithDefaults instantiates a new UeContextInSmsfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUeContextInSmsfDataWithDefaults() *UeContextInSmsfData {
	this := UeContextInSmsfData{}
	return &this
}

// GetSmsfInfo3GppAccess returns the SmsfInfo3GppAccess field value if set, zero value otherwise.
func (o *UeContextInSmsfData) GetSmsfInfo3GppAccess() SmsfInfoUdm {
	if o == nil || openapi.IsNil(o.SmsfInfo3GppAccess) {
		var ret SmsfInfoUdm
		return ret
	}
	return *o.SmsfInfo3GppAccess
}

// GetSmsfInfo3GppAccessOk returns a tuple with the SmsfInfo3GppAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeContextInSmsfData) GetSmsfInfo3GppAccessOk() (*SmsfInfoUdm, bool) {
	if o == nil || openapi.IsNil(o.SmsfInfo3GppAccess) {
		return nil, false
	}
	return o.SmsfInfo3GppAccess, true
}

// HasSmsfInfo3GppAccess returns a boolean if a field has been set.
func (o *UeContextInSmsfData) HasSmsfInfo3GppAccess() bool {
	if o != nil && !openapi.IsNil(o.SmsfInfo3GppAccess) {
		return true
	}

	return false
}

// SetSmsfInfo3GppAccess gets a reference to the given SmsfInfoUdm and assigns it to the SmsfInfo3GppAccess field.
func (o *UeContextInSmsfData) SetSmsfInfo3GppAccess(v SmsfInfoUdm) {
	o.SmsfInfo3GppAccess = &v
}

// GetSmsfInfoNon3GppAccess returns the SmsfInfoNon3GppAccess field value if set, zero value otherwise.
func (o *UeContextInSmsfData) GetSmsfInfoNon3GppAccess() SmsfInfoUdm {
	if o == nil || openapi.IsNil(o.SmsfInfoNon3GppAccess) {
		var ret SmsfInfoUdm
		return ret
	}
	return *o.SmsfInfoNon3GppAccess
}

// GetSmsfInfoNon3GppAccessOk returns a tuple with the SmsfInfoNon3GppAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeContextInSmsfData) GetSmsfInfoNon3GppAccessOk() (*SmsfInfoUdm, bool) {
	if o == nil || openapi.IsNil(o.SmsfInfoNon3GppAccess) {
		return nil, false
	}
	return o.SmsfInfoNon3GppAccess, true
}

// HasSmsfInfoNon3GppAccess returns a boolean if a field has been set.
func (o *UeContextInSmsfData) HasSmsfInfoNon3GppAccess() bool {
	if o != nil && !openapi.IsNil(o.SmsfInfoNon3GppAccess) {
		return true
	}

	return false
}

// SetSmsfInfoNon3GppAccess gets a reference to the given SmsfInfoUdm and assigns it to the SmsfInfoNon3GppAccess field.
func (o *UeContextInSmsfData) SetSmsfInfoNon3GppAccess(v SmsfInfoUdm) {
	o.SmsfInfoNon3GppAccess = &v
}

func (o UeContextInSmsfData) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.SmsfInfo3GppAccess) {
		toSerialize["smsfInfo3GppAccess"] = o.SmsfInfo3GppAccess
	}
	if !openapi.IsNil(o.SmsfInfoNon3GppAccess) {
		toSerialize["smsfInfoNon3GppAccess"] = o.SmsfInfoNon3GppAccess
	}
	return toSerialize, nil
}

type NullableUeContextInSmsfData struct {
	value *UeContextInSmsfData
	isSet bool
}

func (v NullableUeContextInSmsfData) Get() *UeContextInSmsfData {
	return v.value
}

func (v *NullableUeContextInSmsfData) Set(val *UeContextInSmsfData) {
	v.value = val
	v.isSet = true
}

func (v NullableUeContextInSmsfData) IsSet() bool {
	return v.isSet
}

func (v *NullableUeContextInSmsfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUeContextInSmsfData(val *UeContextInSmsfData) *NullableUeContextInSmsfData {
	return &NullableUeContextInSmsfData{value: val, isSet: true}
}

func (v NullableUeContextInSmsfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUeContextInSmsfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
