// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Unified Data Repository Service API file for subscription data

Unified Data Repository Service (subscription data).
The API version is defined in 3GPP TS 29.504.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: -

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// UeSubscribedDataSetName All values defined as ProvisionedDataSetName or ContextDataSetName are applicable
type UeSubscribedDataSetName string

// List of UeSubscribedDataSetName
const (
	UESUBSCRIBEDDATASETNAME_AMF_3_GPP         UeSubscribedDataSetName = "AMF_3GPP"
	UESUBSCRIBEDDATASETNAME_AMF_NON_3_GPP     UeSubscribedDataSetName = "AMF_NON_3GPP"
	UESUBSCRIBEDDATASETNAME_SDM_SUBSCRIPTIONS UeSubscribedDataSetName = "SDM_SUBSCRIPTIONS"
	UESUBSCRIBEDDATASETNAME_EE_SUBSCRIPTIONS  UeSubscribedDataSetName = "EE_SUBSCRIPTIONS"
	UESUBSCRIBEDDATASETNAME_SMSF_3_GPP        UeSubscribedDataSetName = "SMSF_3GPP"
	UESUBSCRIBEDDATASETNAME_SMSF_NON_3_GPP    UeSubscribedDataSetName = "SMSF_NON_3GPP"
	UESUBSCRIBEDDATASETNAME_SUBS_TO_NOTIFY    UeSubscribedDataSetName = "SUBS_TO_NOTIFY"
	UESUBSCRIBEDDATASETNAME_SMF_REG           UeSubscribedDataSetName = "SMF_REG"
	UESUBSCRIBEDDATASETNAME_IP_SM_GW          UeSubscribedDataSetName = "IP_SM_GW"
	UESUBSCRIBEDDATASETNAME_ROAMING_INFO      UeSubscribedDataSetName = "ROAMING_INFO"
	UESUBSCRIBEDDATASETNAME_PEI_INFO          UeSubscribedDataSetName = "PEI_INFO"
	UESUBSCRIBEDDATASETNAME_AM                UeSubscribedDataSetName = "AM"
	UESUBSCRIBEDDATASETNAME_SMF_SEL           UeSubscribedDataSetName = "SMF_SEL"
	UESUBSCRIBEDDATASETNAME_SMS_SUB           UeSubscribedDataSetName = "SMS_SUB"
	UESUBSCRIBEDDATASETNAME_SM                UeSubscribedDataSetName = "SM"
	UESUBSCRIBEDDATASETNAME_TRACE             UeSubscribedDataSetName = "TRACE"
	UESUBSCRIBEDDATASETNAME_SMS_MNG           UeSubscribedDataSetName = "SMS_MNG"
	UESUBSCRIBEDDATASETNAME_LCS_PRIVACY       UeSubscribedDataSetName = "LCS_PRIVACY"
	UESUBSCRIBEDDATASETNAME_LCS_MO            UeSubscribedDataSetName = "LCS_MO"
	UESUBSCRIBEDDATASETNAME_LCS_BCA           UeSubscribedDataSetName = "LCS_BCA"
	UESUBSCRIBEDDATASETNAME_LCS_SUB           UeSubscribedDataSetName = "LCS_SUB"
	UESUBSCRIBEDDATASETNAME_V2_X              UeSubscribedDataSetName = "V2X"
	UESUBSCRIBEDDATASETNAME_PROSE             UeSubscribedDataSetName = "PROSE"
	UESUBSCRIBEDDATASETNAME_ODB               UeSubscribedDataSetName = "ODB"
	UESUBSCRIBEDDATASETNAME_EE_PROF           UeSubscribedDataSetName = "EE_PROF"
	UESUBSCRIBEDDATASETNAME_PP_PROF           UeSubscribedDataSetName = "PP_PROF"
	UESUBSCRIBEDDATASETNAME_NIDD_AUTH         UeSubscribedDataSetName = "NIDD_AUTH"
	UESUBSCRIBEDDATASETNAME_USER_CONSENT      UeSubscribedDataSetName = "USER_CONSENT"
	UESUBSCRIBEDDATASETNAME_MBS               UeSubscribedDataSetName = "MBS"
	UESUBSCRIBEDDATASETNAME_PP_DATA           UeSubscribedDataSetName = "PP_DATA"
	UESUBSCRIBEDDATASETNAME_A2_X              UeSubscribedDataSetName = "A2X"
	UESUBSCRIBEDDATASETNAME_UE_UPD_CONF       UeSubscribedDataSetName = "UE_UPD_CONF"
)

// All allowed values of UeSubscribedDataSetName enum
var AllowedUeSubscribedDataSetNameEnumValues = []UeSubscribedDataSetName{
	"AMF_3GPP",
	"AMF_NON_3GPP",
	"SDM_SUBSCRIPTIONS",
	"EE_SUBSCRIPTIONS",
	"SMSF_3GPP",
	"SMSF_NON_3GPP",
	"SUBS_TO_NOTIFY",
	"SMF_REG",
	"IP_SM_GW",
	"ROAMING_INFO",
	"PEI_INFO",
	"AM",
	"SMF_SEL",
	"SMS_SUB",
	"SM",
	"TRACE",
	"SMS_MNG",
	"LCS_PRIVACY",
	"LCS_MO",
	"LCS_BCA",
	"LCS_SUB",
	"V2X",
	"PROSE",
	"ODB",
	"EE_PROF",
	"PP_PROF",
	"NIDD_AUTH",
	"USER_CONSENT",
	"MBS",
	"PP_DATA",
	"A2X",
	"UE_UPD_CONF",
}

func (v *UeSubscribedDataSetName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UeSubscribedDataSetName(value)
	if slices.Contains(AllowedUeSubscribedDataSetNameEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid UeSubscribedDataSetName", value)
}

// NewUeSubscribedDataSetNameFromValue returns a pointer to a valid UeSubscribedDataSetName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUeSubscribedDataSetNameFromValue(v string) (*UeSubscribedDataSetName, error) {
	ev := UeSubscribedDataSetName(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for UeSubscribedDataSetName: valid values are %v", v, AllowedUeSubscribedDataSetNameEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UeSubscribedDataSetName) IsValid() bool {
	return slices.Contains(AllowedUeSubscribedDataSetNameEnumValues, v)
}

// Ptr returns reference to UeSubscribedDataSetName value
func (v UeSubscribedDataSetName) Ptr() *UeSubscribedDataSetName {
	return &v
}

type NullableUeSubscribedDataSetName struct {
	value *UeSubscribedDataSetName
	isSet bool
}

func (v NullableUeSubscribedDataSetName) Get() *UeSubscribedDataSetName {
	return v.value
}

func (v *NullableUeSubscribedDataSetName) Set(val *UeSubscribedDataSetName) {
	v.value = val
	v.isSet = true
}

func (v NullableUeSubscribedDataSetName) IsSet() bool {
	return v.isSet
}

func (v *NullableUeSubscribedDataSetName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUeSubscribedDataSetName(val *UeSubscribedDataSetName) *NullableUeSubscribedDataSetName {
	return &NullableUeSubscribedDataSetName{value: val, isSet: true}
}

func (v NullableUeSubscribedDataSetName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUeSubscribedDataSetName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
