// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nsmf_PDUSession

SMF PDU Session Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// TrafficProfile Possible values are: - SINGLE_TRANS_UL: Uplink single packet transmission. - SINGLE_TRANS_DL: Downlink single packet transmission. - DUAL_TRANS_UL_FIRST: Dual packet transmission, firstly uplink packet transmission   with subsequent downlink packet transmission. - DUAL_TRANS_DL_FIRST: Dual packet transmission, firstly downlink packet transmission   with subsequent uplink packet transmission.
type TrafficProfile string

// List of TrafficProfile
const (
	TRAFFICPROFILE_SINGLE_TRANS_UL     TrafficProfile = "SINGLE_TRANS_UL"
	TRAFFICPROFILE_SINGLE_TRANS_DL     TrafficProfile = "SINGLE_TRANS_DL"
	TRAFFICPROFILE_DUAL_TRANS_UL_FIRST TrafficProfile = "DUAL_TRANS_UL_FIRST"
	TRAFFICPROFILE_DUAL_TRANS_DL_FIRST TrafficProfile = "DUAL_TRANS_DL_FIRST"
	TRAFFICPROFILE_MULTI_TRANS         TrafficProfile = "MULTI_TRANS"
)

// All allowed values of TrafficProfile enum
var AllowedTrafficProfileEnumValues = []TrafficProfile{
	"SINGLE_TRANS_UL",
	"SINGLE_TRANS_DL",
	"DUAL_TRANS_UL_FIRST",
	"DUAL_TRANS_DL_FIRST",
	"MULTI_TRANS",
}

func (v *TrafficProfile) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TrafficProfile(value)
	if slices.Contains(AllowedTrafficProfileEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid TrafficProfile", value)
}

// NewTrafficProfileFromValue returns a pointer to a valid TrafficProfile
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTrafficProfileFromValue(v string) (*TrafficProfile, error) {
	ev := TrafficProfile(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for TrafficProfile: valid values are %v", v, AllowedTrafficProfileEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TrafficProfile) IsValid() bool {
	return slices.Contains(AllowedTrafficProfileEnumValues, v)
}

// Ptr returns reference to TrafficProfile value
func (v TrafficProfile) Ptr() *TrafficProfile {
	return &v
}

type NullableTrafficProfile struct {
	value *TrafficProfile
	isSet bool
}

func (v NullableTrafficProfile) Get() *TrafficProfile {
	return v.value
}

func (v *NullableTrafficProfile) Set(val *TrafficProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableTrafficProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableTrafficProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrafficProfile(val *TrafficProfile) *NullableTrafficProfile {
	return &NullableTrafficProfile{value: val, isSet: true}
}

func (v NullableTrafficProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrafficProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
