// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nnwdaf_AnalyticsInfo

Nnwdaf_AnalyticsInfo Service API.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"

	"github.com/omec-project/openapi/v2"
)

// checks if the EndpointAddress type satisfies the MappedNullable interface at compile time
var _ openapi.MappedNullable = &EndpointAddress{}

// EndpointAddress struct for EndpointAddress
type EndpointAddress struct {
	Hostname *string `json:"hostname,omitempty" yaml:"hostname,omitempty"`
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166.
	Ipv4Addr *string `json:"ipv4Addr,omitempty" yaml:"ipv4Addr,omitempty" validate:"regexp=^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$"`
	// String identifying an IPv6 address formatted according to clause 4 of RFC5952. The mixed IPv4 IPv6 notation according to clause 5 of RFC5952 shall not be used.
	Ipv6Addr *string `json:"ipv6Addr,omitempty" yaml:"ipv6Addr,omitempty" validate:"regexp=^(((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3}))))|((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?)))$"`
	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
	PortNumber int32 `json:"portNumber" yaml:"portNumber"`
}

// NewEndpointAddress instantiates a new EndpointAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointAddress(portNumber int32) *EndpointAddress {
	this := EndpointAddress{}
	this.PortNumber = portNumber
	return &this
}

// NewEndpointAddressWithDefaults instantiates a new EndpointAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointAddressWithDefaults() *EndpointAddress {
	this := EndpointAddress{}
	return &this
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *EndpointAddress) GetHostname() string {
	if o == nil || openapi.IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointAddress) GetHostnameOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *EndpointAddress) HasHostname() bool {
	if o != nil && !openapi.IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *EndpointAddress) SetHostname(v string) {
	o.Hostname = &v
}

// GetIpv4Addr returns the Ipv4Addr field value if set, zero value otherwise.
func (o *EndpointAddress) GetIpv4Addr() string {
	if o == nil || openapi.IsNil(o.Ipv4Addr) {
		var ret string
		return ret
	}
	return *o.Ipv4Addr
}

// GetIpv4AddrOk returns a tuple with the Ipv4Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointAddress) GetIpv4AddrOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.Ipv4Addr) {
		return nil, false
	}
	return o.Ipv4Addr, true
}

// HasIpv4Addr returns a boolean if a field has been set.
func (o *EndpointAddress) HasIpv4Addr() bool {
	if o != nil && !openapi.IsNil(o.Ipv4Addr) {
		return true
	}

	return false
}

// SetIpv4Addr gets a reference to the given string and assigns it to the Ipv4Addr field.
func (o *EndpointAddress) SetIpv4Addr(v string) {
	o.Ipv4Addr = &v
}

// GetIpv6Addr returns the Ipv6Addr field value if set, zero value otherwise.
func (o *EndpointAddress) GetIpv6Addr() string {
	if o == nil || openapi.IsNil(o.Ipv6Addr) {
		var ret string
		return ret
	}
	return *o.Ipv6Addr
}

// GetIpv6AddrOk returns a tuple with the Ipv6Addr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointAddress) GetIpv6AddrOk() (*string, bool) {
	if o == nil || openapi.IsNil(o.Ipv6Addr) {
		return nil, false
	}
	return o.Ipv6Addr, true
}

// HasIpv6Addr returns a boolean if a field has been set.
func (o *EndpointAddress) HasIpv6Addr() bool {
	if o != nil && !openapi.IsNil(o.Ipv6Addr) {
		return true
	}

	return false
}

// SetIpv6Addr gets a reference to the given string and assigns it to the Ipv6Addr field.
func (o *EndpointAddress) SetIpv6Addr(v string) {
	o.Ipv6Addr = &v
}

// GetPortNumber returns the PortNumber field value
func (o *EndpointAddress) GetPortNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PortNumber
}

// GetPortNumberOk returns a tuple with the PortNumber field value
// and a boolean to check if the value has been set.
func (o *EndpointAddress) GetPortNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PortNumber, true
}

// SetPortNumber sets field value
func (o *EndpointAddress) SetPortNumber(v int32) {
	o.PortNumber = v
}

func (o EndpointAddress) ToMap() (map[string]any, error) {
	toSerialize := map[string]any{}
	if !openapi.IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !openapi.IsNil(o.Ipv4Addr) {
		toSerialize["ipv4Addr"] = o.Ipv4Addr
	}
	if !openapi.IsNil(o.Ipv6Addr) {
		toSerialize["ipv6Addr"] = o.Ipv6Addr
	}
	toSerialize["portNumber"] = o.PortNumber
	return toSerialize, nil
}

type NullableEndpointAddress struct {
	value *EndpointAddress
	isSet bool
}

func (v NullableEndpointAddress) Get() *EndpointAddress {
	return v.value
}

func (v *NullableEndpointAddress) Set(val *EndpointAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointAddress(val *EndpointAddress) *NullableEndpointAddress {
	return &NullableEndpointAddress{value: val, isSet: true}
}

func (v NullableEndpointAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
