// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Namf_Communication

AMF Communication Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// UeCommOrderCriterion Represents the ordering criterion for the list of UE communication analytics.   Possible values are:     - START_TIME: The ordering criterion of the analytics is the start time.   - DURATION: The ordering criterion of the analytics is the duration of the communication.
type UeCommOrderCriterion string

// List of UeCommOrderCriterion
const (
	UECOMMORDERCRITERION_START_TIME UeCommOrderCriterion = "START_TIME"
	UECOMMORDERCRITERION_DURATION   UeCommOrderCriterion = "DURATION"
)

// All allowed values of UeCommOrderCriterion enum
var AllowedUeCommOrderCriterionEnumValues = []UeCommOrderCriterion{
	"START_TIME",
	"DURATION",
}

func (v *UeCommOrderCriterion) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UeCommOrderCriterion(value)
	if slices.Contains(AllowedUeCommOrderCriterionEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid UeCommOrderCriterion", value)
}

// NewUeCommOrderCriterionFromValue returns a pointer to a valid UeCommOrderCriterion
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUeCommOrderCriterionFromValue(v string) (*UeCommOrderCriterion, error) {
	ev := UeCommOrderCriterion(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for UeCommOrderCriterion: valid values are %v", v, AllowedUeCommOrderCriterionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UeCommOrderCriterion) IsValid() bool {
	return slices.Contains(AllowedUeCommOrderCriterionEnumValues, v)
}

// Ptr returns reference to UeCommOrderCriterion value
func (v UeCommOrderCriterion) Ptr() *UeCommOrderCriterion {
	return &v
}

type NullableUeCommOrderCriterion struct {
	value *UeCommOrderCriterion
	isSet bool
}

func (v NullableUeCommOrderCriterion) Get() *UeCommOrderCriterion {
	return v.value
}

func (v *NullableUeCommOrderCriterion) Set(val *UeCommOrderCriterion) {
	v.value = val
	v.isSet = true
}

func (v NullableUeCommOrderCriterion) IsSet() bool {
	return v.isSet
}

func (v *NullableUeCommOrderCriterion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUeCommOrderCriterion(val *UeCommOrderCriterion) *NullableUeCommOrderCriterion {
	return &NullableUeCommOrderCriterion{value: val, isSet: true}
}

func (v NullableUeCommOrderCriterion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUeCommOrderCriterion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
