// Copyright (C) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
Nudr_DataRepository API OpenAPI file

Unified Data Repository Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
*/

package models

import (
	"encoding/json"
	"slices"

	"github.com/omec-project/openapi/v2"
)

// AuthMethod Contains the Authentication Method.
type AuthMethod string

// List of AuthMethod
const (
	AUTHMETHOD__5_G_AKA      AuthMethod = "5G_AKA"
	AUTHMETHOD_EAP_AKA_PRIME AuthMethod = "EAP_AKA_PRIME"
	AUTHMETHOD_EAP_TLS       AuthMethod = "EAP_TLS"
	AUTHMETHOD_EAP_TTLS      AuthMethod = "EAP_TTLS"
	AUTHMETHOD_NONE          AuthMethod = "NONE"
)

// All allowed values of AuthMethod enum
var AllowedAuthMethodEnumValues = []AuthMethod{
	"5G_AKA",
	"EAP_AKA_PRIME",
	"EAP_TLS",
	"EAP_TTLS",
	"NONE",
}

func (v *AuthMethod) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuthMethod(value)
	if slices.Contains(AllowedAuthMethodEnumValues, enumTypeValue) {
		*v = enumTypeValue
		return nil
	}

	return openapi.ReportError("%+v is not a valid AuthMethod", value)
}

// NewAuthMethodFromValue returns a pointer to a valid AuthMethod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuthMethodFromValue(v string) (*AuthMethod, error) {
	ev := AuthMethod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, openapi.ReportError("invalid value '%v' for AuthMethod: valid values are %v", v, AllowedAuthMethodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuthMethod) IsValid() bool {
	return slices.Contains(AllowedAuthMethodEnumValues, v)
}

// Ptr returns reference to AuthMethod value
func (v AuthMethod) Ptr() *AuthMethod {
	return &v
}

type NullableAuthMethod struct {
	value *AuthMethod
	isSet bool
}

func (v NullableAuthMethod) Get() *AuthMethod {
	return v.value
}

func (v *NullableAuthMethod) Set(val *AuthMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthMethod(val *AuthMethod) *NullableAuthMethod {
	return &NullableAuthMethod{value: val, isSet: true}
}

func (v NullableAuthMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
